### ISSUE TITLE
Images/Banners/Logos in collabs

### ISSUE THREAD

**Issue by Skayo** [devRant/devRant#10]
It would be nice if you could add some images, banners or logos to your collabs.

**Comment by Skayo** [comment]
The banner, for example would be at the top of the collab.

The logo, for example would be in list of collabs and somewhere in the collab.

And additionally you can add one more image, which is displayed at the bottom of the collab. (like in normal rants)

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DFoxinator** [comment]
Going to close this for now, right now we’re going to leave collabs as-is.
