### ISSUE TITLE
Multi window support for Samsung devices. 

### ISSUE THREAD

**Issue by ibrahimabdo** [devRant/devRant#102]
It would be nice to have multi window support for Samsung phones.

**Comment by tankerkiller125** [comment]
This is a feature that's now part of Android itself, I think making it compatible with all Android devices running the right version of Android would be perfectly fine as Device specific multi-window support gets extremely bulky quickly.

**Comment by ibrahimabdo** [comment]
Sure. Supporting native multi window is even better. But also adding support for Samsung will include devices with lower Android version. I don't think it will bloat the code since both implementations require about two lines of code in the AndroidManifest file.

**Comment by cozyplanes** [comment]
Possible duplicate with #9

**Comment by Skayo** [comment]
Duplicate of #9
