### ISSUE TITLE
Add new collab error 

### ISSUE THREAD

**Issue by daegontaven** [devRant/devRant#104]
It gives me this error.
![collab](https://i.imgur.com/rmMu0G0.png) 

I tried clearing the local cache for the app to no avail.

**Comment by RekkyRek** [comment]
It's because .io DNS servers are having some problems and since devRant uses a .io domain the app sometimes can't connect to the api. It'll probably be fixed within a day.

**Comment by daegontaven** [comment]
@RekkyRek Thanks for updating me on the issue.

**Comment by DFoxinator** [comment]
Thanks for reporting this - I think we spoke on the app, should be fixed now :)
