### ISSUE TITLE
[feature request] Option to disable "read more"

### ISSUE THREAD

**Issue by flintstone1409** [devRant/devRant#105]
It would be nice to have an option to have the complete rant shown in the feed instead of having to open it (like it is in the WebApp). The same would be nice for images, especially with slower internet connections it often takes a long time to load the rant or image again, which is already loaded. And it makes reading unnecessarily complicated.

Edit: I am kind-of new to this github thing (and coding stuff), how do I add labels? Or can they only be added by @DFoxinator and @trogus?

**Comment by tisaconundrum2** [comment]
#78

**Comment by flintstone1409** [comment]
Well sorry... I read all the "Issues" but somehow I must have overlooked that... Sorry
