### ISSUE TITLE
Android 8.0

### ISSUE THREAD

**Issue by Haxk20** [devRant/devRant#106]
I cannot get notifs when app is closed at all I must open app each time I want so see notifs. (I font get notifications outside of app)
Solution adapt devRant app with 8.0 standard then use api 26.

**Comment by RekkyRek** [comment]
Same. I think it has to do with the new battery saving features of Android.

**Comment by Haxk20** [comment]
no android doze was introduced in 6.0 it worked fine there and even 7 if it was battery saver then simply disabling it for devRant will solve this but that's not the case issue is that devRant still don't use notification channels so it cannot post notifs properly.

**Comment by RekkyRek** [comment]
@Haxk20 I was not talking about the battery saving feature, they've tweaked the way apps are allowed to run in the background and other stuff like that.

**Comment by Haxk20** [comment]
Issue resolved. Can be closed.
