### ISSUE TITLE
Black theme glitch in notifs list on iOS

### ISSUE THREAD

**Issue by JakubSteplowski** [devRant/devRant#109]
I noticed that sometimes the color of the "icon" at the left of the notification is black instead of gray.
It happens when you open a "marked as new" notifications and then go back.

![2](https://user-images.githubusercontent.com/4522930/30777456-32cdfd08-a0bb-11e7-8e11-971fda23cadb.jpg)
![3](https://user-images.githubusercontent.com/4522930/30777455-32c79396-a0bb-11e7-9c58-099731462772.jpg)
![1](https://user-images.githubusercontent.com/4522930/30777454-32c72528-a0bb-11e7-8b98-0906881b95eb.jpg)

**Comment by DFoxinator** [comment]
Thanks for reporting! We issued a fix for this on Android a couple of days ago and iOS will have a new release tomorrow :)

**Comment by LoganS1** [comment]
is this fixed? If so it should be closed
