### ISSUE TITLE
Rant got deleted while writing. 

### ISSUE THREAD

**Issue by DanielVZ96** [devRant/devRant#112]
It wasn't just randomly deleted. I got a  call while I was writing it and the app went a bit nuts: it closed the writting view, reloaded and left me in the main screen. When I tapped the new rant button, I expected to still have what I was writing there but it wasn't. It took me to the category view. This may be a problem of my phone. Maybe it resets apps during calls. I'll look into it, but I wanted to share this as it was quite frustrating. (a wall of text lost :( )

**Comment by calmyourtities** [comment]
I think you'll need to provide some more info

**Comment by DFoxinator** [comment]
I'm guessing this is probably because the app closed or something while you still had the post window open. The only time we guarantee rants/comments are saved as drafts is when you close the post window. However, we probably want to better that functionality and make it so they get auto-saved too beyond only when the window closes.

**Comment by LoganS1** [comment]
Maybe DevRant could save the drafts based on time (Say every 5 seconds + on window close)? I am guessing with this that the data is saved locally on the phone otherwise this answer would probably spam the databases.

**Comment by DFoxinator** [comment]
@LoganS1 yeah that's what I was kind of thinking, just putting save on a timer too instead of only on the window close event. We save all drafts locally.

**Comment by DanielVZ96** [comment]
@DFoxinator Yeah, I was thinking that most probably, the call somehow made the app reload and thus making the saved rant be lost. It would be cool if Rants could be saved locally somehow. Thanks for the attention 😄
