### ISSUE TITLE
Cannot save images from within app on iOS

### ISSUE THREAD

**Issue by electrux** [devRant/devRant#116]
The app crashes when I click the “save image” button on any image. I tried reinstalling, rebooting and both didn’t work.
I do think it is crashing as it finishes downloading since there is a delay between clicking the button, and app crashing.

I am on iOS 11, iPhone 6s.

**Comment by electrux** [comment]
Sorry forgot to mention,
I am on iOS 11, iPhone 6s.

**Comment by DFoxinator** [comment]
Thank you for reporting this issue. There was an issue with iOS 11 and saving images. It should be fixed in the version we just release that should be available for download now (v 1.9.7).

Sorry about that and thanks again!

**Comment by electrux** [comment]
Wow!! That is fast!! Thanks a lot for being so amazing developers and for giving us an amazing community 😄
