### ISSUE TITLE
Mention users in rants

### ISSUE THREAD

**Issue by Skayo** [devRant/devRant#13]
It's a thing that everyone would like to have...
Why are you against it?

If it's because you don't want ranters to rant about someone specific: What's the difference between "fake mentioning" him in the rant then write a comment in wich you mention him (everyone does that) and mentioning someone directly in the rant itself?

**Comment by NicholasBatesNZ** [comment]
The thing is, not everyone does this "fake mentioning" that you speak of. Granted, there are a few people that do the comment mentioning, there would be many more direct rants at a particular person if tagging was supported in the original rant.
I agree with many devRant users that this should NOT be implemented as most of the 50,000 of us that have downloaded the app do not want to see a message directed at one or a few people. 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DFoxinator** [comment]
I agree with @NicholasBatesNZ and that's the reason we haven't implemented this feature.

Yes, people do it anyway, but I fear people would do it more often if it was something we actually allowed. Rants really shouldn't be used as a way to mention other users IMO.

**Comment by cozyplanes** [comment]
No for me

**Comment by DFoxinator** [comment]
I'm going to close this out for now. From some more feedback we've gathered I don't think this is something that would improve the overall experience of the community and we don't want to encourage using rants as communication to specific users really. We plan to implement some kind of private messaging system which will be more for that I think.

**Comment by theabbie** [comment]
Not a necessary feature in my opinion, Rants are for everyone, And you can do it like people do it usually, mention in Rants as well as in comments. There is nothing wrong in that.
