### ISSUE TITLE
Colour coded notifications

### ISSUE THREAD

**Issue by coolq1000** [devRant/devRant#135]
## The idea,
Sometimes when I'm scrolling through all my DevRant notifications I end up scrolling through lots of ++'s(thanks everyone!). Perhaps it would be a nice idea to colour code them so that we can simply skim through and quickly see what's important.

## An example,
I see that I have 23 notifications, I click over to that tab, then I see notifications that are coloured due to their importance. Maybe yellow for mentions, perhaps no highlight on ++'s, and it would be nice to have a blue tint on comments on your rant.

- thoughts?

**Comment by Parou** [comment]
I think that's a great idea. It would make the notifications so much clearer. It would be easier to spot mentions and comments in 50+ notifications. I don't know, maybe it would even be possible to put notifications in two categories, like one tab for ++'s and one for direct interactions (comments, mentions, etc.) I get like 50 -100 notifications on a normal day. If I would not look at devRant for a day or two, I would easily not be able to check every mention or other important notifications.

**Comment by coolq1000** [comment]
@Parou
Thanks for your input! I think you'd still want a combined tab though. I hope they consider these ideas 😉

**Comment by PerhapsSomeone** [comment]
I definitely agree. Make it happen.

**Comment by RekkyRek** [comment]
@DFoxinator please do this. also, would be awesome to sort notifs by importance!

**Comment by DFoxinator** [comment]
Good idea, I think closely related to https://github.com/devRant/devRant/issues/5

**Comment by coolq1000** [comment]
Good to see that other issues pose a similar questions, if you'd like to follow this issue, then be sure to add in colours!

**Comment by trogus** [comment]
I have the same problem, the plan has been to break notifs up into tabs for the different categories

**Comment by coolq1000** [comment]
@trogus

Sounds good, although I do think that colours aswell would give it a nice touch 😉
(sorry to keep pushing for colours, just think it's a good solution)

**Comment by DFoxinator** [comment]
Closing this in favor of https://github.com/devRant/devRant/issues/113 which is almost done. We tested color coded with the filter notif types, and the colors didn't really add much and made it a little too busy. The notif tabs will make it really easy to view specific notif types.
