### ISSUE TITLE
Selecting the sorting order of rants broken in Edge

### ISSUE THREAD

**Issue by JamJar00** [devRant/devRant#139]
In Edge selecting the sorting order of rants (using e.g. Top) does nothing and raises an error in the JavaScript console:
![image](https://user-images.githubusercontent.com/5931310/31149997-e84a1bc8-a889-11e7-8564-8cd870a95286.png)
It appears to work fine in Firefox.

**Comment by DFoxinator** [comment]
Closing this, new website has officially launched!
