### ISSUE TITLE
Unvalidated URL Field

### ISSUE THREAD

**Issue by ksdme** [devRant/devRant#143]
I just noticed the following collab's url field, it says 'http://no url yet'. So I guess its because of an unvalidated field in the submission form and I am also too lazy to verify if that exists on the mobile version too.

**Comment by DFoxinator** [comment]
Thanks for the report! I'm not sure I exactly understand the problem. Can you try to describe some additional details? Where are you seeing this issue and what is it exactly? Is it on a specific collab?

**Comment by DFoxinator** [comment]
Closing this for now, if you have any more information feel free to add it.
