### ISSUE TITLE
devducks details looks weird

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#145]
do you know the feature that displays the web page info when there is a url typed in telegram/slack/etc?
when i typed devducks.com, it showed [this](https://i.imgur.com/WUrlF8P.png)

----
**aww the ducks are so cute**

**Comment by DFoxinator** [comment]
Thanks for the report. I believe this is fixed now, can you please check again?

**Comment by cozyplanes** [comment]
not here yet...

**Comment by davidbgeek** [comment]
This is fixed. We were checking on Telegram and we were getting the cached preview. Taking a look here: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fdevducks.com, it is indeed working. Thanks.

**Comment by cozyplanes** [comment]
not here yet

**Comment by cozyplanes** [comment]
working. Great!

**Comment by DFoxinator** [comment]
@cozyplanes thanks and thanks for confirming! And thanks @davidbgeek!
