### ISSUE TITLE
Login popup event when logged in

### ISSUE THREAD

**Issue by skyyyme** [devRant/devRant#147]
I am already logged on in devrant.io. When i visit https://devrant.io/ and click login it takes me to feed and popup comes up even i am already logged in. 

Its nothing major just annoying.

**Comment by 7twin** [comment]
@DFoxinator Just noticed after encountering this bug for a long time: it's fixed by just going to "Rant feed" instead of clicking "Login" - but a quick check if somebody is logged in and not pop it up should be possible too.

**Comment by DFoxinator** [comment]
Closing this, new website has officially launched!
