### ISSUE TITLE
Cannot view profiles on Android app

### ISSUE THREAD

**Issue by StefanJanssen95** [devRant/devRant#15]
**Device:** LG G2
**Android version:** 4.4.2

I cannot view profiles on my phone. Pressing a name or profile image doesn't do anything and to view the profile I have to open the unofficial UWP version on my other phone or the website. I've had this since I joined (2/5/2017).

**Comment by cozyplanes** [comment]
this looks fixed now and seems to be his device issue.

**Comment by StefanJanssen95** [comment]
It indeed seems to be fixed, therefor I will close this issue.
