### ISSUE TITLE
Printable Template for devDucks Cape

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#150]
https://www.devrant.io/rants/897431/cheap-mans-devduck 

As mentioned here, i would like to have a printable template for devDucks cape.
Yeah, it will probably decrease your profit, but plz consider. Thanks.

**Comment by Skayo** [comment]
Hey these guys need to eat too!

**Comment by RekkyRek** [comment]
i don't think this is doable since the capes aren't paper. They are some kind of vinyl material to be stretchable.

**Comment by cozyplanes** [comment]
Just a template to print... I mean the outlines

**Comment by cozyplanes** [comment]
Just an idea

**Comment by DFoxinator** [comment]
Interesting idea, but I think what @RekkyRek said is the main problem. The material we use is stretchable so it makes it so you can get the cape over the duck's head and it fits nicely. Paper ones would have to be big around the neck and then would stay on very loosely. 

We can definitely look into it, but my guess is there's no way we'd be able to offer anything even close to the quality we want to for something like that and it wouldn't be a great representation of the quality of the real ones.

**Comment by cozyplanes** [comment]
ok then, thanks for considering tho

**Comment by DFoxinator** [comment]
Closing for now, as wouldn’t be able to do this and maintain any kind of quality/usability with paper.
