### ISSUE TITLE
Wrong notification count

### ISSUE THREAD

**Issue by Parou** [devRant/devRant#151]
I get a lot of notifications sometimes but they usually stop around a count of 50 - 58. After that I don't get new notifications until I clear my notification list. It doesn't only affect the displayed count at the notification icon in the app, I really don't get new notifications in the list when it stops increasing.
 It happens on both, Android and the web version.

Is that intended? (Because some months ago when I got as many notifications sometimes, it didn't stop randomly at 50 - 58)

~ Alice

**Comment by DFoxinator** [comment]
Thanks for the report!

This is a very weird one. Normally I would have suspected it was something to do with the Android app but if it does it on the web version too then that's very odd. I'm not sure what it can be.

Do you have any other details you might be able to provide?

**Comment by Parou** [comment]
hm... I don't know what else I could say about it because it happens on Android and the web version.
Well, I have a Sony Xperia XA with Android 7 and use Google Chrome in the current stable version on Windows 10.

I first noticed it when some users started to ++ many of my rants and comments again as it's commom at the moment and I realized that I still got more ++ at my profile although my notifications stopped. So I cleared my notifications everytime I noticed this and it continued to give me new notifications, but only notifications that are created after clearing the list (I missed some mentions because of this and was very confused the first time I saw some mentions that I didn't get).

Most of the time it stops right away exactly at 50, but sometimes I get some more notifications. The highest count I got since this happens were 58 before I needed to clear my notifications.


I hope that helps in a way.


~ Alice

**Comment by devRant** [comment]
@Parou thanks for the detailed information!

Can you please let me know next time you have it happening, before clearing your notifs?

**Comment by DFoxinator** [comment]
@Parou thanks for the detailed information!

Can you please let me know next time you have it happening, before clearing your notifs?

**Comment by Parou** [comment]
I just tested it out with my girlfriend when I had 58 notifications again. Now I have 62 and everything seems to work like it should.

It seems to only happen when someone gives many ++'s in a short time (That's what happened everytime when I noticed that) because that's the only difference this time.


~ Alice

**Comment by DFoxinator** [comment]
I'm pretty sure I figured out what this was, and I think it should be fixed now :) Please let me know if you encounter it again, thanks!
