### ISSUE TITLE
Dislike-Mafia prevention

### ISSUE THREAD

**Issue by wholl0p** [devRant/devRant#153]
The algorithm should prevent people from downvoting too much. With too much I mean like 50 downvotes in 2 minutes! Happens way too often that people downvote all your rants because of reasons only they understand.

**Comment by DFoxinator** [comment]
Thanks for the suggestion! We implemented something similar very recently and it prevents the exact behavior you describe. I don't want to lay out exactly how it works since it is meant to combat abusers, but rest assured it will not allow for the scenario you described to occur.
