### ISSUE TITLE
Disappearing/Locked Buttons

### ISSUE THREAD

**Issue by NiftyCola** [devRant/devRant#158]
When I press the "+" button, "clear" button or any button that has a shade of orange/red it disappears and briefly flashes a few times.
The "+" button while scrolling through rants will be completely gone but is still usable in this state, as are the other buttons as well.
Some buttons like the back button while trying to exit a profile or exiting a drafted rant, it will acknowledge that you have pressed it by turning a slightly darker shade but does not do anything half of the time. (This is the back button **in** the app, not on the actual device)
This is on the mobile version, the website version does not have these problems for me.

**Comment by DFoxinator** [comment]
Thanks for the report. What platform are you using the mobile app on?

**Comment by NiftyCola** [comment]
@DFoxinator I am using Android

_Sent from my Galaxy Note3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DFoxinator** [comment]
Please re-open this if this still happens, but I think by now this should have been fixed.
