### ISSUE TITLE
Open the rant's image directly from the preview

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#16]
It's really annoying that you have to click on the rant, then wait, then click on the image if you just want to see the image (not the rant...)
To open an image directly, you have to long-press on it. (To prevent from opening the image accidentally if you actually wanted to open the rant)

With GIFs this is currently possible but not with images.

**Comment by StefanJanssen95** [comment]
I always want to open the rant as well if I want to see the image. If clicking on the image would load the image it is difficult to open a rant when there is (almost) no other content. I find this annoying with the GIFs myself.

**Comment by mediadeo** [comment]
the previews are also not loading anymore ... pls enhance

**Comment by Skayo** [comment]
@mediadeo Please open a new issue for this
