### ISSUE TITLE
devRant Android app vulnerable to Lucky Patcher

### ISSUE THREAD

**Issue by moriczgergo** [devRant/devRant#162]
Tried to get supporter with Lucky Patcher, worked successfully. Revoke my supporter, I'm skiilaa in the app.

**Comment by DFoxinator** [comment]
Thanks for the report. Can you please provide more details on this? I don't see anything to indicate the user skiilaa was ever marked as a supporter and that user is not a supporter.

**Comment by moriczgergo** [comment]
Hmmmm, the app says the purchase was successful. Then I guess the app isn’t vulnerable then, but it reports success on fail too.

**Comment by DFoxinator** [comment]
Thanks, going to close this, only concern here would be if people were able to subscribe, but doesn't' seem that's possible.
