### ISSUE TITLE
Mardown support

### ISSUE THREAD

**Issue by theCalcaholic** [devRant/devRant#163]
Markdown support would be an amazing improvement for devRant - especially proper code rendering.

Thanks for the great work!

PS: `sudo add-markdown-support`

**Comment by cozyplanes** [comment]
Possible duplicate of #27
Please search first as duplicate issues will be closed immediately

**Comment by DFoxinator** [comment]
Thanks for the suggestion! This feature suggestion is being tracked here: https://github.com/devRant/devRant/issues/27 (feel free to discuss!)

**Comment by theCalcaholic** [comment]
Ah, thank you. A search for 'markdown' did not yield any result, so I wasn't aware there's is a ticket already.
