### ISSUE TITLE
Only sell ducks for $SOME-PRICE-HERE

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#166]
Probably unneeded, but yeah, a feature!

**Comment by LoganS1** [comment]
Did you mean "show" ducks for $SOME-PRICE or are you talking about making all ducks the same price?

**Comment by DFoxinator** [comment]
Closing - we have no plans to sell ducks alone.

**Comment by cozyplanes** [comment]
np

2018-01-18 14:45 GMT+09:00 David Fox <notifications@github.com>:
