### ISSUE TITLE
devRant Recruitment/Referral Programme

### ISSUE THREAD

**Issue by akalpokas** [devRant/devRant#168]
I want to suggest a feature, that would allow current devRant users to recruit new users into the community. Each user would have an unique link that would be easy to share. After a new user registers with that link, and maybe reaches a certain amount of points/rants, the recruiter could be awarded with some kind of an award such as a shiny new 'Recruiter' badge or whatever. I think this would be a great way to help expand the community, without relying on new users to find the app accidentally like I did. Of course certain measures should be put in place to prevent abuse.

**Comment by cozyplanes** [comment]
duplicate accounts will increase to get those stupid rewards

**Comment by Audy47** [comment]
Like I said above, this should come with a system to check for legit invites and fake ones. And to you these rewards may be stupid, but if you have a better plan to allow current users to invite people, then I'm all ears.

**Comment by DFoxinator** [comment]
Thank you for this constructive growth idea/brainstorming. I think something like this could be really cool and we're always looking for new ways to grow the community. I think some incentive is definitely possible and we could do could fairly easily to some abuse checking. Also, if someone was really going to game the system, I doubt anyone would want to risk having their account deleted for getting fake users.

I'm curious to hear some more thoughts on this. But I think something like this can be very effective and a good additional avenue for the expansion of the community and rewarding members who help by showing the app to their friends.

**Comment by AlgoRythm-Dylan** [comment]
I suggest the referred user must reach 500 ++ before the referrer get any reward.
