### ISSUE TITLE
Scrolling to the bottom

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#173]
Rants that have a lot of comments are hard to scroll through, this could be solved by either:

- using accelerated scrolling like native apps (the faster you swipe, the more you scroll)
- having a scroll to bottom button
- remembering what the last message was one read in a rant and then scrolling to that message (similar to discord)

**Comment by DFoxinator** [comment]
Thanks for the suggestion - this is in progress - closing as duplicate of https://github.com/devRant/devRant/issues/97
