### ISSUE TITLE
Duplicate sharing options

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#178]
When pressing the grey share button in rants, i dont understand why there is facebook, twitter sharing again in the dialog box.

![screenshot](https://i.imgur.com/jOAmqqv.png)

**Comment by DFoxinator** [comment]
Since it's just the icons on the rant screen, we have them spelled out in the share menu.

**Comment by cozyplanes** [comment]
how about changing the grey share button to grey clipboard button?
