### ISSUE TITLE
Refresh icon idea

### ISSUE THREAD

**Issue by Gerrymandered** [devRant/devRant#183]
What if the refresh icon was in the title bar instead?

**Comment by Gerrymandered** [comment]
![img_0395_720](https://user-images.githubusercontent.com/26412287/31623213-c13e889c-b26c-11e7-8bd6-f30f21a59b3e.jpg)

**Comment by DFoxinator** [comment]
We were going to do that at first. However, we thought it would be weird to tap a refresh button at the top of the screen and have the comments refresh and be added to the bottom of the screen. Doesn't seem like natural placement for that.

**Comment by 7twin** [comment]
@DFoxinator I would like to agree with the suggestion rather than the current implementation, since one is just more used to either pull to refresh or press a refresh button at the top, this would also solve #177

**Comment by 7twin** [comment]
@DFoxinator this can be closed with the newest update rolled out

**Comment by DFoxinator** [comment]
@7twin thanks, I will close this after the iOS build goes live. It's still waiting for review.

**Comment by DFoxinator** [comment]
All app updates have been released!
