### ISSUE TITLE
Newly upvoted rants have a red number, previous ones don't

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#185]
See related rant:

https://www.devrant.io/rants/922917/just-upvoted-comments-rants-have-a-red-number-instead-of-previously-upvoted-comm

**Comment by DFoxinator** [comment]
Thanks - I believe this is a theme-specific issue, I'm guessing only the light theme maybe, but I will confirm.

**Comment by DFoxinator** [comment]
I think this was fixed, please let me know if it pops up again. Thanks!
