### ISSUE TITLE
Line-breaks in WebApp

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#19]
Android:
![In Android App](https://s1.postimg.org/7y0us0q9b/IMG_20170802_092944.jpg)

WebApp:
![In Web App](https://s1.postimg.org/jdya2adzj/IMG_20170802_092911.png)

As you can see there are no line-breaks in the  WebApp... Maybe fix that?

**Comment by Skayo** [comment]
Wait a sec... The website isn't displayed in the WebApp... dafuq?
Is that right/normal?
