### ISSUE TITLE
Collab limitations

### ISSUE THREAD

**Issue by skerp972** [devRant/devRant#190]
Either reinstate the collab creation price or cheaper, or add a minimum of characters needed for both summary and description.

50 chars min for the "summary"
and 500 chars min for the "description"

https://www.devrant.io/collabs/928295/chatbot

**Comment by cozyplanes** [comment]
Setting default chars for each item would look nice, but i dont understand about the price you are talking about. Currently, collabs are free.

**Comment by skerp972** [comment]
@cozyplanes The collabs weren't free a few weeks ago, a collab costed $9,99 for non-devRant++ members.
But I guess you remember better because you are a member since way longer than me.

**Comment by cozyplanes** [comment]
@skerp972 no problem then!

**Comment by trogus** [comment]
@skerp972 There is a tiny character minimum for a rant, and a collab post is a type of rant. If it's not valuable as is (doesn't look like it unless it's supposed to be a joke), feel free to downvote it and it will be shown to fewer people.

Also Collabs is not long for the main nav, will likely end up as a type filter and probably on the more menu list. Lots of attention to a such limited set of posts doesn't make that much sense.  We had hope they would have taken off, but it didn't happen. Learn and iterate!
