### ISSUE TITLE
Is there a limit in notif counts displayed?

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#195]
It seems there is a limit in notifs view. About 99.
And notifs seems to be cut off below 99.
I lost about 9 upvotes button.
I think at least unviewed notifs should be shown, rather than hidden. 
Or, am I wrong?

**Comment by DFoxinator** [comment]
There is a limit of 100. Very soon we'll have a notif tab for each notif type, so you will get 100 of each of those too so in addition to seeing the last 100 of everything, you can also see the last 100 of any specific type.

**Comment by cozyplanes** [comment]
thank you!
