### ISSUE TITLE
[bug] [website] Cannot load more collabs 

### ISSUE THREAD

**Issue by aayush26** [devRant/devRant#199]
In the website:  
When I open collab https://devrant.com/collabs/   
And click **More rants**, it redirects me to https://devrant.com/feed/recent/2 which returns rants feed and does not load the next n collabs.

**Comment by DFoxinator** [comment]
For now I removed the paging - this will be better-addressed in our web app overhaul, but for now you can see all the collabs. Thanks for the report!

**Comment by aayush26** [comment]
@DFoxinator  Is a new webapp being developed currently?

**Comment by cozyplanes** [comment]
i guess so

**Comment by DFoxinator** [comment]
@aayush26 yes, a completely new web app is nearing completion.
