### ISSUE TITLE
Rant saving feature doesn't work for tags

### ISSUE THREAD

**Issue by Mitiko** [devRant/devRant#20]
devRant has introduced the feature of autosaving the rant if not posted, though this does not save the tags that were provided

**Comment by ShellAddicted** [comment]
This issue affect also media attachment of the rant

**Comment by Mitiko** [comment]
@ShellAddicted This might be a problem if the user deletes the image before posting the rant...

**Comment by ShellAddicted** [comment]
@Mitiko of course, anyway it is annoying.

**Comment by DFoxinator** [comment]
This behavior is fixed in our latest release!

We still don't save images, and if someone wants to make a separate issue then they can, but there's very little priority to implement that since it's a good amount of work and any images should be very easy to attach again.
