### ISSUE TITLE
Banning and warning people that reach a certain amount of -- and preventing cheating by deleting content

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#203]
Currently if people have a certain amount of -- they seem to be not able to post, but many just bypass this by deleting all of their content and restarting it all over again, the community has often times suggested a feature of automatic banning or cooldowning those accounts if they reach some certain amount - maybe even preventing them from using any content functions like deleting (to remove any --), editing (to maybe fake what the original message actually says in the range of 30 minutes) and more. The bans could be done in levels, so after reaching -5 total you would get a certain amount of cooldown and then at the maximum of -10 or -15 you would get banned.

**Comment by DFoxinator** [comment]
We have some more of this we turned on that pretty much does exactly what you said, or at least makes it very hard to fall under the threshold once you pass it.
