### ISSUE TITLE
new .com domain wasn't added to the Facebook app for sharing rants yet

### ISSUE THREAD

**Issue by Parou** [devRant/devRant#205]
After the domain change from .io to .com, you still need to add the new domain to the Facebook app whose app id is being used by the share dialogue.

See (In german, it basically says that the domain from which it tries to share isn't included in the domains of the app, so it doesn't work):
![devrant com](https://user-images.githubusercontent.com/28531401/31929327-e413d8a6-b89b-11e7-9d40-8ebd84906f6d.png)

**Comment by ksdme** [comment]
Something on a vaguely related note, devRant's Github repo itself needs an url update.
![image](https://user-images.githubusercontent.com/12156014/31940171-ccabe53e-b8da-11e7-84df-6c01294aa730.png)

**Comment by DFoxinator** [comment]
Thanks a bunch for reporting this issue. I changed the domain on the Facebook page but forgot to add it to the Facebook app. It should be fixed now.

I also changed our GitHub profile.
