### ISSUE TITLE
Swag page needs updating 

### ISSUE THREAD

**Issue by Gerrymandered** [devRant/devRant#206]
I presume the new email now ends in .com since the new domain switch? Also there’s a mix on ++’s and +1’s. Correct me if I’m wrong, didn’t we switch to pure ++’s?

**Comment by Gerrymandered** [comment]
Link:
https://devrant.com/free-stickers?ref=appswag

**Comment by cozyplanes** [comment]
and the swags below needs to be updated to the latest ducks as well

**Comment by DFoxinator** [comment]
Language updated, emails will be updated eventually but old ones are still in use.
