### ISSUE TITLE
Feature Request: Styling (bold, italic, underline)

### ISSUE THREAD

**Issue by JakubSteplowski** [devRant/devRant#207]
Hi,

I was thinking recently about this missing feature.
What about the possibility to insert bold, italic and underline text inside the rants?

I understand it could ruin the general design appearance of the app if users would start to abuse it, but maybe sometimes it could be useful, for example if you want to separate different paragraphs or highlight a particular sentence inside the rant.

Or maybe something different to separate the paragraphs (separators, titles, etc.), or emphasize a sentence (quotes, etc.).

Let me know if is something you thought about and don't implement for some reason, or is something could really be interesting.

**Comment by DFoxinator** [comment]
Thanks for the suggestion :)

It's definitely something we're considering. We have a discussion going for this on this issue: https://github.com/devRant/devRant/issues/27 So it probably makes sense to continue it there.

Some of the concerns you expressed are definitely ones we've had, so please chime in with those in that discussion, more thoughts on this are appreciated.
