### ISSUE TITLE
User's Website not showing in WebApp?

### ISSUE THREAD

**Issue by Skayo** [devRant/devRant#21]
Android:
![In Android App](https://s1.postimg.org/7y0us0q9b/IMG_20170802_092944.jpg)

WebApp:
![In Web App](https://s1.postimg.org/jdya2adzj/IMG_20170802_092911.png)

As you can see, the website (skayo.github.io) is not showing in the WebApp!  Why's that?

**Comment by DFoxinator** [comment]
Closing this, new website has officially launched!
