### ISSUE TITLE
Meme prevention does only work on clientside

### ISSUE THREAD

**Issue by stop5** [devRant/devRant#210]
While browsing I saw this rant: https://devrant.io/rants/955063 .
I am sure that the picture was already posted. So could you have a look at this?

**Comment by cozyplanes** [comment]
Looks like it is a mistake between the user of devRantron, not the official devRant app.

**Comment by DFoxinator** [comment]
Yeah, I'm not sure what this means. Duplicate image detection is done on the backend and likely devRantron is just not set up to handle the error or something.
