### ISSUE TITLE
Suggestion: Video Attachments

### ISSUE THREAD

**Issue by joas8211** [devRant/devRant#211]
## The problem
I've seen many rants featuring an attached animated GIF as a video and many times the loading has been really **slow**. An animated GIF is not really good for a day-to-day video format because it doesn't feature a proper video compression. It has a lossless per-frame compression which is great for simple animations but nowhere near enough for recordings. For that reason you often find animated GIFs that are destroyed by a low resolution.

## Potential solution
Motion compression like H.264 would help drastically for example with screen captures. It would be best done on server side where you can also apply length, sound and resolution limitations and manipulations.

This is trading more computation to lower file size and greater user experience.

**Comment by cozyplanes** [comment]
Looks like a nice feature, but the server costs will be deadly. Of course, no devs will upload a movie, but a couple of seconds really takes some MBs.

**Comment by AlgoRythm-Dylan** [comment]
I frequently use devRant in situations where I cannot use audio. This would be a very resource-expensive feature which I would just ignore most of the time.

**Comment by joas8211** [comment]
Just to clear things up: I meant that a more compact file format could replace GIF but that doesn't mean necessarily that should have more length or audio. We could also just convert GIFs to other video format to have smaller file sizes. In the best situation it wouldn't even change the way users use the app, it would just be a performance boost.

**Comment by cozyplanes** [comment]
I feel the only way that dfox will not panic in those server costs is to make optional monthly in app purchases of a feature to upload videos.

**Comment by AlgoRythm-Dylan** [comment]
I just really don't think it's worth the effort

**Comment by joas8211** [comment]
Closed, because loading times have gotten better. IDK if it's more performant server or just my internet connection. And nobody doesn't seem to care about it, so why bother.

**Comment by joas8211** [comment]
Closed, because loading times have gotten better. IDK if it's more performant server or just my internet connection. And nobody doesn't seem to care about it, so why bother.

**Comment by joas8211** [comment]
Closed, because loading times have gotten better. IDK if it's more performant server or just my internet connection. And nobody doesn't seem to care about it, so why bother.
