### ISSUE TITLE
Links need updated in DB

### ISSUE THREAD

**Issue by LoganS1** [devRant/devRant#213]
I just noticed while reading some rants that their are links to the old "devrant.io" domain. If you ever decided to leave the io domain behind or it was down because of the io issues, the links would not work. Would it be possible to run a query to change all devrant.io links to devrant.com links?

**Comment by DFoxinator** [comment]
We'll always have devrant.io. I don't think it's worth it to update actual post text - the redirect is fine for stuff like that.
