### ISSUE TITLE
GIFs don't play

### ISSUE THREAD

**Issue by retnikt** [devRant/devRant#220]
I'm on Android (Marshmallow 6.0.1, Samsung Galaxy S5) and when I open a GIF it just gives me an endless spinner:
![screenshot_2017-10-31-15-35-49](https://user-images.githubusercontent.com/24581770/32233180-b8812264-be51-11e7-9aab-52720866eef5.png)
I don't think this is a connection issue, as normal images load fine and I can view them by clicking "Save Image" then opening it, and I'm not sure if it's just me with this problem. I can't confirm this for iOS, but they load on the Web App. ~ retnikt

**Comment by AlgoRythm-Dylan** [comment]
Happens to me as well.

**Comment by Parou** [comment]
Same here on Android 7.0

**Comment by tankerkiller125** [comment]
Same here 7.1

**Comment by Henex** [comment]
Same Android 7.0.1

**Comment by DFoxinator** [comment]
This should be fixed, please let me know if anyone experiences any further issues. Thanks!
