### ISSUE TITLE
Collab loads as rant

### ISSUE THREAD

**Issue by Skayo** [devRant/devRant#23]
This is just for you to keep track of issues.
[Related Rant](https://www.devrant.io/rants/644855/bug-report-description-if-you-go-to-the-comments-section-on-your-profile-and-cli)

**Comment by Skayo** [comment]
You have already fixed that.
I only created this issue so you know what you have changed.
(Look at the comments of the rant)

**Comment by DFoxinator** [comment]
This should be fixed in a previous release.
