### ISSUE TITLE
Wrong icon in notifs

### ISSUE THREAD

**Issue by Skayo** [devRant/devRant#24]
This is just for you to keep track of issues.
[Related Rant](https://www.devrant.io/rants/577212/atdfox-attrogus-my-god-i-just-realized-the-icon-next-to-the-avatar-is-wrong-for)

**Comment by tisaconundrum2** [comment]
![image](https://user-images.githubusercontent.com/11879769/28902170-33438b40-77b2-11e7-8945-d1fb4485c202.png)

**Comment by Skayo** [comment]
@dfox
I think @trogus already fixed that.
I only created this issue so you know what you have changed.

**Comment by trogus** [comment]
Not fixed yet, will do soon

**Comment by Skayo** [comment]
Oh theres a completely new icon now!
I'll close this issue now.
