### ISSUE TITLE
Header has flickering pixels

### ISSUE THREAD

**Issue by SindbadClauss** [devRant/devRant#242]
If you open a ran which has many comments and scroll up and down a little there are some pixels in the header ("Rant") which turn white and stay so.

**Comment by cozyplanes** [comment]
Phone rendering issue?

**Comment by SindbadClauss** [comment]
For me it's only on devRant.

**Comment by DFoxinator** [comment]
What platform are you using? Device, OS version? Do you have a screenshot or anything to show this behavior?

Thanks!

**Comment by SindbadClauss** [comment]
Somehow I can't reproduce this anymore. So fixed, I guess...
