### ISSUE TITLE
Possible missing feature - Scroll to bottom for rants with images

### ISSUE THREAD

**Issue by japorized** [devRant/devRant#249]
There seems to be no option to scroll to bottom in the context menu for **certain** rants with images, at least that's what I noticed on the iOS app.

Edit: As I submit that and went to another rant, that option was somehow available in **certain** rants but not the others.

**Comment by japorized** [comment]
Did not want to add another edit to the main post, so I'll put it as a comment.

Is the scroll to bottom feature only available after the post has a certain amount of replies?

**Comment by cozyplanes** [comment]
@japorized yes it is, check dfox post

**Comment by japorized** [comment]
Alrighty. That was my bad then. Closing this.
