### ISSUE TITLE
Are old usernames tracked?

### ISSUE THREAD

**Issue by AlgoRythm-Dylan** [devRant/devRant#252]
Not sure if this is a feature request... more of a *does feature exist* kind of thing, but when you change your username, is your username history stored? Will this be/is this available via the public API?

**Comment by cozyplanes** [comment]
@AlgoRythm-Dylan dont think so... If the user deletes the username, lets say Tom, or when the person who had the username Tom changed his username, it gets available to others instantly.

More like a bool value whether Tom can be used or not.

Just my interpretation, not sure. @DFoxinator

**Comment by AlgoRythm-Dylan** [comment]
@cozyplanes  Well of course, the username is freed, a username history would make no differences on that.

**Comment by DFoxinator** [comment]
We keep a record of the most recent change for each user, but we don't expose it in any API calls and currently don't use it for anything.

**Comment by DFoxinator** [comment]
Not sure if there's a request here, but if so feel free to write it up in a new issue, thanks.
