### ISSUE TITLE
Cannot able to attach Image/GIF in comments [WebApp]

### ISSUE THREAD

**Issue by khateeb321** [devRant/devRant#254]

**Comment by cozyplanes** [comment]
Webapp overhaul coming soon, and i remember there is a similar issue saying the same problem.

**Comment by Skayo** [comment]
Possible duplicate of #11

**Comment by DFoxinator** [comment]
Thanks for the report - closing as duplicate of https://github.com/devRant/devRant/issues/11 and will be covered in new website.
