### ISSUE TITLE
Samsung S8+ strange design issues

### ISSUE THREAD

**Issue by ValonK** [devRant/devRant#255]
I'm experiencing this issues, not sure why.

![screenshot_20171114-233803](https://user-images.githubusercontent.com/23531499/33063489-e87b46e6-cea2-11e7-934e-691404544ea0.png)

![screenshot_20171009-004328](https://user-images.githubusercontent.com/23531499/33063492-eb9e7df2-cea2-11e7-822a-c44aa191dd3e.jpg)

**Comment by LoganS1** [comment]
Posted an issue then I saw yours, here was my post which I believe is related:

Just updated my Galaxy S8 and noticed they implement the ability to lock and unlock the navigation bar from the bottom of the screen. I noticed that when unlocking the bar the screen glitches. Even if I restart the app the with nav bar unlocked the glitch occurs. Pics included [HERE.](https://imgur.com/a/msqwi)

**Comment by DFoxinator** [comment]
This should have been fixed in a recent version. Please let me know if it's still around, thanks.
