### ISSUE TITLE
Rant refresh button double click

### ISSUE THREAD

**Issue by bsonntag** [devRant/devRant#262]
If a rant's refresh button is double clicked the comments are loaded twice.

Tested on the Android app.

**Comment by Skayo** [comment]
Can confirm

**Comment by Kimmax** [comment]
Not directly tied to doubled tapping, if you manged to do 4-5 taps before the rant loads, you end up with 4-5 times the comments

**Comment by Kimmax** [comment]
Actually duplicate of #258

**Comment by bsonntag** [comment]
@Kimmax you're right, sorry about that. Closing this in favor of #258.
