### ISSUE TITLE
Non-Image feed

### ISSUE THREAD

**Issue by Kimmax** [devRant/devRant#264]
Please introduce an algo'ed no-image feed
devRant grew a good chunk over the last months, which introduced more users that push devRant more into a IT-Meme direction.
I would find it very sad if we start to see less quality rants,  since they to don't seem to be worth it anymore (memes get more ++'ses for less effor in a much shorter time, _if you even care about that_) and eye's automagically get's more attracted to pictures than text
Thanks for considering :)

**Comment by Parou** [comment]
Ooor we could just finally put the meme / joke category into its own tab and sanction memes that are posted in the other category.

We already have that category as a choice when we create a new rant.

**Comment by Kimmax** [comment]
True

**Comment by skerp972** [comment]
If only the rants categories were working and if we could sort the type of rants.

**Comment by mrlinnth** [comment]
"Hide meme from feed" option like repost.
Or easiest might be not showing any image on feed page and show attached image only when you read it.

**Comment by DFoxinator** [comment]
This will be addressed by the view rant type selector. That selector will apply globally so you can choose which kinds of rants you want to see for any view. That should accomplish what you're looking for, I would think.

**Comment by Kimmax** [comment]
Hey @DFoxinator _might_ I ask what time frame we are speaking of? Weeks or Months? :)

**Comment by DFoxinator** [comment]
@Kimmax probably about a month or a little less. Depends on how quickly we can finish up the new web version which is priority #1 and almost done.

**Comment by DFoxinator** [comment]
Closing as this will be available soon under type selector.
