### ISSUE TITLE
Projects Page: DevRant-Stats

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#275]
Hello devRant-Team!

I recently started a little devRant-Stats Website with various stats and infos!
The website is currently only available (or interesting) for devRant++ Members because there is no good way to get a list of all users (and make stats available for everyone).
It's still in the development but you can already use it. (There will be more interesting features coming soon)
Just ask if you have any questions.
I'd be very happy if you add this to the projects page!

Website: [https://devrant-stats.github.io](https://devrant-stats.github.io)
GitHub: [https://github.com/DevRant-Stats/devrant-stats.github.io](https://github.com/DevRant-Stats/devrant-stats.github.io)

**Comment by Ewpratten** [comment]
I really like this website idea! Here is a devCredits page / link for you and your project:

https://devcredits.herokuapp.com/?title=devRant%20Stats&subtext=%20&users=Skayo&color=4

feel free to use it (or not.. but it would be nice)

**Comment by Skayo** [comment]
@Ewpratten Thanks but I made it completely by myself and no one helped me (until now). Would be strange to have a credits page...

**Comment by Skayo** [comment]
Yo @dfox if you ever add it, would be nice if you could also add my DevRant-API-Docs Site!

> https://devrant-docs.github.io

**Comment by Skayo** [comment]
Also add this please:
https://github.com/devRant-Squad/awesome-devrant
