### ISSUE TITLE
[Feature Request] Indicator for orignalRanter

### ISSUE THREAD

**Issue by Bobj2018** [devRant/devRant#282]
# The Feature
The idea is to make an indicator so that it is eaiser to tell if the original Ranter commented on his/her rant.

## Highlighting Username
Adding a stroke around the username that has the same color as the avatar background 

## Colored Box
Similar to the supporter ++, the box will have the same color as the avatar background and have [oR] originalRanter or [*]

**Comment by qbasic16** [comment]
It would also be cool to just add a box like the one for supporters [++] but with "OR" or similar in it: [OR]

I think this way it would not change the appearance or the current layout.
