### ISSUE TITLE
Poor performance in notification list

### ISSUE THREAD

**Issue by Demiko** [devRant/devRant#287]
After latest update (1.11) notification list began lagging considerably

**Comment by DFoxinator** [comment]
Can you please add your Android version, device, etc.?

**Comment by Demiko** [comment]
Android version: 6.0.1 (MIUI 9)
Device: Xiaomi Redmi 4 (regular version, not Pro os X)

Performance issues are only in notifications lists (filtered and unfiltered), other lists (rants and comments) perform normally

**Comment by DFoxinator** [comment]
This should be fixed now, thanks.
