### ISSUE TITLE
Image zoom is broken

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#290]
As the title says, zooming into pictures is broken with the newest update:
- pinch to zoom is disabled completely
- doubletap zooming allows to zoom only into one point, after that navigating to any direction shows the animation as if the image ends there

Android 7.1.2

**Comment by retnikt** [comment]
Cannot reproduce, android 6.0.1

**Comment by kaesaecracker** [comment]
Can reproduce, Android 8

**Comment by paradonym** [comment]
Can't reproduce, OnePlus 3T, Android 8

but double tap zooming opens the "save image" menu which should open on singletap+hold (okay, which is a part of doubletap zooming...)

**Comment by DFoxinator** [comment]
This was fixed in a previous version, so closing. Thanks.
