### ISSUE TITLE
Greeting avatar in splash screen

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#3]
Was mentioned before by someone else

----
Would like a feature that my avatar shows up in splash screen by optional because it may slow the app starting performance.

**Comment by DFoxinator** [comment]
I remember when this was posted someone explained a possible way to do this, but I have to find that rant. Do you by any chance remember which one it was?

**Comment by DFoxinator** [comment]
I changed the title of this because we'll be using the tag to designate feature requests. Makes it easier to read the issues.

**Comment by cozyplanes** [comment]
Sorry for making this messy, will find out

**Comment by DFoxinator** [comment]
@cozyplanes thanks!

**Comment by RekkyRek** [comment]
From what I've gathered it's really hard to do in Appcelerator since it's loaded before the app.

**Comment by cozyplanes** [comment]
😭😭😭

**Comment by DFoxinator** [comment]
Going to close this, while cool, seems like it would be very difficult to do in Titanium and impossible to do on iOS.
