### ISSUE TITLE
[Web] ++ button hidden when adblock is on

### ISSUE THREAD

**Issue by haithamsboui** [devRant/devRant#315]
Adblock adds some css rules with "display:none" that contains .plusone .

- Google Chrome V.60.0.3112.113 
- AdBlock V.3.24.0

`<style>
::content .share-box, ::content .share-link-container, ::content .social-wrap, ::content .social_container, ::content a[href="http://www.twellow.com/"], ::content #to-the-top, ::content .scroll_top, ::content #digg_upcoming_content, ::content .clk-pinit, ::content .fb-dialog, ::content .share-menu, ::content .share-wrapper, ::content a[href^="https://twitter.com/intent/follow?"], ::content #sharebox, ::content .-twitter, ::content .button-social, ::content .custom-social, ::content .share-options, ::content .social-column, ::content .socialButtons, ::content .twitterWrapper, ::content img[alt="Youtube"], ::content .follow-btn, ::content .share_bar, ::content img[alt="submit to reddit"], ::content #cookieAlert, ::content #cookiebox, ::content #___plusone_0, ::content .btn-fb, ::content .facebook_button, ::content .g-plusone, ::content .icon-facebook, ::content .pinterest-share-button, ::content .shareContent, ::content .sharecontainer, ::content .social-facebook, ::content .std-social, ::content .twitter-follow-button, ::content img[alt="Facebook"], ::content #backTop, ::content .btn-reddit, ::content .share-group, ::content .social-bar-container, ::content .youtube-link, ::content img[title="YouTube"], ::content .icon-rss, ::content #vk_right, ::content .social-google, ::content .socialmedia, ::content .twitter-share-button, ::content .cookieInfo, ::content .addthis_default_style, ::content .fb_edge_widget_with_comment, ::content img[alt="Pinterest"], ::content .addthisbuttons, ::content .fb-box, ::content .twBox, ::content #subscribe-button, ::content .cookie-warn, ::content .social_wrapper, ::content .ssk-facebook, ::content .twitterShare, ::content .wrapper-share, ::content img[alt="Twitter"], ::content .footer-newsletter, ::content #button_facebook, ::content #shareMenu, ::content #socialContainer, ::content .fblike, ::content .pin-it-button, ::content .retweet, ::content .share-panel, ::content .show_social, ::content .tweets, ::content img[alt="facebook"], ::content .pinterest-button, ::content .twitter-button, ::content img[title="Facebook"], ::content #share-links, ::content .navbar-social, ::content .pinterest1, ::content #backtotop, ::content #sharevideo, ::content a[href^="http://twitter.com/?status="], ::content img[alt="Google+"], ::content #social-header, ::content #tweets, ::content .m-article__share-buttons, ::content #socialbar, ::content .post-share-panel, ::content .cookie_consent, ::content #social_bar, ::content .button-pinterest, ::content .cookie-policy, ::content #button_twitter, ::content #sharebuttons, ::content .follow_twitter, ::content .socialboxp, ::content .facebook-button, ::content .fb-recommendations-bar, ::content #outbrain_widget_0, ::content .btn-google-plus, ::content .social-post, ::content .rss.icon, ::content #advancedsocialwidget, ::content #vk-popup, ::content .icon-fb, ::content .social-links, ::content #fbContainer, ::content .btnFacebook, ::content .social-login, ::content .js-follow-user, ::content .like-box, ::content .fb-content, ::content .fb_share, ::content .share-widget, ::content a[href^="https://pinterest.com/pin/create/"], ::content .socialBox, ::content #layout-social, ::content #twitter_button, ::content .fb-likebox, ::content .search-social, ::content .social-count, ::content .socialbutton, ::content .linkedin.icon, ::content .OUTBRAIN, ::content .follow-label, ::content .sharing-buttons, ::content .rssFeed, ::content #social-container, ::content #vk_groupsVK, ::content .btn-social-icon, ::content .plusone, ::content .fb_btn, ::content .image-share, ::content .share_panel, ::content a[href^="http://twitter.com/share?"], ::content .addthis_toolbox, ::content .follow-widget, ::content .socials, ::content a[href^="http://www.pinterest.com/pin/create/button/?"], ::content #facebook_button, ::content #sharebar, ::content .post-sharing, ::content .share-with-friends, ::content .shareToolsItem, ::content .block-subscribe, ::content .cookies-info, ::content .top-of-page, ::content #share-bar, ::content #subscribe-options, ::content .-facebook, ::content .custom-sharing-link, ::content .follow_box, ::content .google-plus, ::content .socialButton, ::content .subscribe-widget, ::content .accept-cookie, ::content .follow-bar, ::content .icon_gplus, ::content .pinit-button, ::content .post_share, ::content .share-popup, ::content .social-counter, ::content .socialbuttons, ::content #subscriptionModal, ::content .SocialButton, ::content .g-plus, ::content .sharebuttons, ::content img[title="LinkedIn"], ::content .rss-feed, ::content .outbrain, ::content #likebtn, ::content .fbBox, ::content .share_container, ::content .twitter-icon, ::content .youtube-icon, ::content #cookieOverlay, ::content #vk_invite_wrapper, ::content .digg-button, ::content .icon-flickr, ::content .icon-soundcloud, ::content .sharelink, ::content .social_block, ::content .close-wrap > .close-overlay, ::content .icon-google-plus-sign, ::content .share-item, ::content a[href^="http://vkontakte.ru/share.php?"], ::content img[alt="LinkedIn"], ::content .scroll-to-top, ::content .fb_like_container, ::content .shareText, ::content .social-wrapper, ::content .social_tabs, ::content .stumble-button, ::content a[href^="http://www.stumbleupon.com/submit?"], ::content .cookie-wall, ::content #to-top, ::content .scrolltop, ::content .advanced-social-widget {
    display: none;
} 
</style>`

![image](https://user-images.githubusercontent.com/5289663/35752521-8b52cf9a-085c-11e8-908a-fc7cf1471eae.png)

**Comment by cozyplanes** [comment]
Fixed in new web app @DFoxinator
