### ISSUE TITLE
Weekly Rants cut on the bottom

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#320]
I you scroll down in the weekly rant list, the last rant is a bit cut.
See here:

[![IMG_20180212_121641.png](https://s17.postimg.org/6wocd1hdr/IMG_20180212_121641.png)](https://postimg.org/image/t8m56fghn/)

**Comment by DLMousey** [comment]
Could you highlight where it's cutting? I don't see anything out of the ordinary.
Looks like normal scrolling behaviour to me

**Comment by Skayo** [comment]
@DLMousey
At the bottom?

**Comment by cozyplanes** [comment]
Can be reproduced. all the time
@DFoxinator
