### ISSUE TITLE
It's possible to subscribe to your own rants

### ISSUE THREAD

**Issue by toloveru** [devRant/devRant#321]
Apparently the devRant app for Android (possibly other platforms too) allows a user to subscribe to their own rants. Granted, only the most desperate among us (i.e. me apparently :sweat_smile:) would actually find out about this.. I was tired, all right... Anyway, it doesn't seem to be desirable behavior?

**Comment by cozyplanes** [comment]
I like it though... 😄

**Comment by DFoxinator** [comment]
We've been aware of this for a while, but we ended up leaving because it can provide some additional security if someone compromises your account and posts, and there doesn't seem to be any adverse effects.
