### ISSUE TITLE
Do not disable control center in the app

### ISSUE THREAD

**Issue by GMR516** [devRant/devRant#324]
There’s no reason to disable iOS control and notification centers when you swipe down. Leave them enabled.

**Comment by DFoxinator** [comment]
Are there any more details you can provide for this? We don't do anything specific around that so not sure exactly what would be happening there.

**Comment by GMR516** [comment]
iPhone 5s, cannot swipe up from the bottom of the screen or down to show the notification center. Works once I exit out of the app, but while I'm in it it doesn't work.

**Comment by ckpearson** [comment]
I can’t reproduce this on iOS 11.3

**Comment by GMR516** [comment]
Updated and it works now.
