### ISSUE TITLE
[Web] devRant automatically logs out when I close the tab

### ISSUE THREAD

**Issue by heyypatrick** [devRant/devRant#325]
I always accidentally close my tab, but when I came back, it requires me to login again resulting to multiple times of logins. Is this supposed to be happening?

ps. I already tried clicking the checkbox but still, my account logs out automatically.

How to reproduce:
1. Login your account
2. Close tab for seconds.
3. Go to `devrant.com`
4. Requires you to login again. 

Tech Info:
1. Xenial Linux
2. Chromium v66

**Comment by heyypatrick** [comment]
Damn. Figured it out. There's a `keep me signed in` checkbox LOL

**Comment by Skayo** [comment]
Maybe some browser settings?
Or what browser are you using?

**Comment by heyypatrick** [comment]
Hmm I'm using the latest version of Chrome. Everytime I close the tab and return it requires me to login again. Though I already checked the `keep me login` checkbox.

**Comment by Skayo** [comment]
Hmm everything works for me...
You sure you didn't turn off cookies or something p

**Comment by heyypatrick** [comment]
My cookies are turned on. I'm using Chrome OS. It keeps on logging out.

**Comment by Skayo** [comment]
Okay no clue what could be wrong. Let's wait for @dfox

**Comment by heyypatrick** [comment]
Tried it. Still on. Sad. Haha thanks, btw!

**Comment by cozyplanes** [comment]
Maybe wait for the new web feed @trogus is working on

**Comment by heyypatrick** [comment]
Woah! Thanks! Looking forward for that new web feed. Thanks!

ps. Still getting the same. Have to login multiple times. Haha

**Comment by trogus** [comment]
I've never encountered this either (tried to repro right now, couldn't get it to log me out) which makes it harder to fix.

The marketing page devrant.com has an uninformed button up top that says "login" no matter what but if you go to devrant.com/feed/ does it recognize that you're logged in? By any chance are you browsing in an incognito window?

**Comment by heyypatrick** [comment]
Hmm don't know why it was like this on my browser. I'm not logged in on incognito either. But, when I close the tab while i'm

**Comment by heyypatrick** [comment]
I think I see the problem:
After closing the tab and I go to `devrant.com/feed`, I'm still logged in. (solves the problem)
But:
After closing the tab and go directly to `devrant.com`, it requires me to log in again.
Last thing:
You can log out by going from `devrant.com/feed` going to `devrant.com` directly without clicking the logout?

Is this supposed to be happening? Seems weird to me. Haha thanks!

**Comment by trogus** [comment]
It's really dumb logic since the marketing page is just a static page I made and the feed has backend wiring to know about your logged in status, so if you click the login button from devrant.com it will open the login modal regardless of whether you are logged or not. If you close the modal without completing it, you will still be logged in. In the situation you're describing, you don't get logged out unless you actively log out, it just looks like it. This should be getting fixed on the new web work @DFoxinator is finishing up (specifically, if you are logged in you will not see the marketing page, devrant.com will land you on the feed right away)

**Comment by heyypatrick** [comment]
Ohh I see, a static page. Thanks @trogus for the insight. Looking forward for the new web feed. Cheers! Now closing the issue. Thanks again!
