### ISSUE TITLE
Unable to become a supporter. Android app. 

### ISSUE THREAD

**Issue by conor-byrne** [devRant/devRant#328]
On clicking the join the devRant supporters button from the menu or headers etc. the confirmation card pops up saying I've subscribed. I'm then brought back to the front page which doesn't load. But that's it. I'm not marked in the supporters list nor my profile have the ++.

I tried uninstalling and reinstalling but got the same result.

I was a supporter in the past but cancelled for a few months. This may or may not be important?

I can't remember from my original subscription but I assume that the Google play order is then supposed to pop up for confirmation? 

Running Android 8.0.0 on a OnePlus3.

**Comment by DFoxinator** [comment]
Hi Conor - thanks for reporting this issue. Does it show you as being subscribed in Google Play? Also, another thing that has worked in the past when issues have popped up is cancelling the subscription in Google Play and then re-subscribing. But to answer your question, I'm pretty sure this has something to do with the cancelled subscription and something on our end getting confused. Sorry about that. I'm trying to think specifically what this might be.

**Comment by conor-byrne** [comment]
Hey! Google play doesn't show me as subscribed unfortunately. 

Have fun figuring out this one, lemme know if you need me to do anything else!

**Comment by conor-byrne** [comment]
Just a note, I subscribed successfully. Assuming you managed to fix it!

**Comment by DFoxinator** [comment]
@conor-byrne thanks for updating this!
