### ISSUE TITLE
Follow rant

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#33]
Ability to follow a rant.
Not adding a meaningless comment in a rant to get updates

**Comment by NicholasBatesNZ** [comment]
This feature has previously been requested in [Issue 6](https://github.com/devRant/devRant/issues/6)


_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cozyplanes** [comment]
@Dfoxinator

Congrats for closing your    
  

# FIRST 
Issue!
