### ISSUE TITLE
When can we expect the API to be publicly available?

### ISSUE THREAD

**Issue by palash25** [devRant/devRant#331]

**Comment by RekkyRek** [comment]
It is

**Comment by palash25** [comment]
can you give me the link?

**Comment by RekkyRek** [comment]
Here are most of the endpoints: https://github.com/RekkyRek/RantScript/blob/master/src/index.js

**Comment by palash25** [comment]
thanks

**Comment by Skayo** [comment]
There's also a docs site made by me:
https://devrant-docs.github.io
Still WIP tho
