### ISSUE TITLE
Webapp - no avatar leads to undefined avatar url in notifs

### ISSUE THREAD

**Issue by romangraef** [devRant/devRant#336]
Having no avatar leads to having the avatar url https://avatars.devrant.com/undefined in the notifs view of the webapp. 
![bugbugbug](https://user-images.githubusercontent.com/20768569/37045624-4b86905c-215e-11e8-9a4e-5dcf91ea1dae.png)

**Comment by DFoxinator** [comment]
Fixed by @trogus
