### ISSUE TITLE
Webapp does not work well on mobile

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#342]
I guess the webapp isn't intended to be used on mobile devices (which would be a shame if that's how its supposed to be) - because theres an install button instead of a login button when you visit the devrant frontpage. But if you force desktop mode, login, turn off desktop mode and visit the feed, theres multiple issues:

1. When scrolling, the logo does not immediately get a background, so the white logo floats above other content:

![image](https://user-images.githubusercontent.com/32747235/37182041-c04839ae-232f-11e8-96b8-74b2becb1bb3.png)

In the same screenshot you can also see #339 

2. There is no user actions in the menubar (no avatar, no notifications, no settings)

**Comment by DFoxinator** [comment]
Thanks for the feedback. I'm going to close this for now. We intentionally support a number of pages on mobile, but simply put, we don't have the resources to support all the functionality and we don't intend to support the feed right now. This will change in the future hopefully, but right now our main concentration is properly supporting our mobile apps, web app, and select functionality on mobile web.
