### ISSUE TITLE
`Delete` does not seem to work

### ISSUE THREAD

**Issue by tisaconundrum2** [devRant/devRant#346]
When trying to delete a rant, the button does not seem to be working. The hyperlink seems to only lead to a `#`

`<a href="#" class="rantlist-delete rantlist-footer-link">Delete</a>`

**Comment by joaofguerreiro** [comment]
@tisaconundrum2 could you label this as Webapp?

**Comment by tisaconundrum2** [comment]
I don't have that power. Only dfox an trogus (or anyone that has collaboration rights to the repo)

**Comment by Skayo** [comment]
Ever heard of Javascript?
