### ISSUE TITLE
Specific rant from the past got bork.

### ISSUE THREAD

**Issue by mcmonkey4eva** [devRant/devRant#348]
https://devrant.com/rants/360493/ouch-xd-at-least-its-getting-better-p

The user data of the poster is missing, the image included is missing, just the rant text and replies are there...

**Comment by DFoxinator** [comment]
Thanks, this happens occasionally, should be removed now!

**Comment by mcmonkey4eva** [comment]
@DFoxinator should I open issues when I see these? Feels like a waste of an issue post just to note some random rant has some but not all of its data deleted.
Like this one: https://devrant.com/rants/226348/you-know-what-would-be-nice-microsoft-listing-your-own-fuckin-platform-in-your-o
:P
