### ISSUE TITLE
devRant Smartphone-Case/Cover

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#35]
I see some people putting devRant Stickers on the back of their smartphone, so why not selling devRant Smartphone-Covers/Cases? :D

**Comment by cozyplanes** [comment]
Ok, 
Iphone 7 plus
Iphone 7
Iphone 6 plus
Iphone 6
....
Samsung galaxy s8
                              s7
                              s6
                           .....

Nokia ....
LG..

Oneplus
 So on...

Can anyone invent a universal phone case?

**Comment by Skayo** [comment]
@cozyplanes 
One design, multiple devices.
There are lots of companies doing this.

**Comment by DFoxinator** [comment]
@Skayo I think it's a really cool idea. Myself, and others I know of, have used the vertical devRant sticker on our phones for a while now.
