### ISSUE TITLE
Search for users/Show users directly in search results

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#364]
**It is a feature I need a lot and I have been waiting long time for:**
Search for a specific user.
This way if you search for someone, you get the profile shown directly in the search results.

_Somehow like this:_
![Example - Search](https://s14.postimage.org/m05gdh5r5/search_With_User.png)

Of course if the search applies to multiple users, there are more shown!
It could be very useful when you search for a user that didn't post any rant yet!

I hope you like the idea!
~ _Skayo_

**Comment by Skayo** [comment]
I had a lot of fun photoshopping that image! hehe

**Comment by DFoxinator** [comment]
Not sure what happened to your image, but I know what you mean and it's a good idea.
