### ISSUE TITLE
Unable to comment

### ISSUE THREAD

**Issue by duckscancode** [devRant/devRant#365]
Im unable to comment on rants.
This is on a Samsung Galaxy S3 running LineageOS 14.1. I'm using the most recent devrant version, and have tried clearing cache, reinstalling etc.

**Comment by duckscancode** [comment]
P.s when I try to comment, it leaves it hanging on the loading symbol, but when I quit and try again, the comment button has no effect

**Comment by DFoxinator** [comment]
Hey - did you ever figure out what this issue was? This seems very isolated and no one else reported any commenting issues. I'm hoping you were able to fix it. Thanks!

**Comment by 7twin** [comment]
@DFoxinator I have had (and have sometimes) the same issue as @duckscancode but it solves itself for me, if you just send the comment again

**Comment by DFoxinator** [comment]
Going to close this for now, if anyone is able to find consistent reproduction steps please let me know. Thanks!
