### ISSUE TITLE
App loading issues

### ISSUE THREAD

**Issue by jatinkr131** [devRant/devRant#367]
In devRant app when I want to upload any rant or any meme it takes very time to load screen, and if I want to see rants from other developers it too takes very much time to load. Please fix the issue

**Comment by DFoxinator** [comment]
Can you please provide more info on your location and what kind of device/internet connection you're using? This issue is almost certainly connection/geographic-related.

**Comment by jatinkr131** [comment]
Whenever I start DevRant in my Moto G4 plus  the app takes appreciable time
to load Rants and images.

**Comment by Skayo** [comment]
This is definitely a phone or internet issue. Also you didn't answer dfox's questions. 
Will close this for now because this is a non-devRant issue. If you can provide more info, just reopen :)
