### ISSUE TITLE
[feature] clicking on the binary ++ changes it to decimal temporarily 

### ISSUE THREAD

**Issue by queenCee** [devRant/devRant#369]
We do know how to read binary, but opening the calculator just to check the number of ++ is a bit tedious.
The binary ++ feature is really cool,adding the click option would be great.

**Comment by queenCee** [comment]
It can be made  a permanent feature,it was nice,just my opinion.

**Comment by 7twin** [comment]
@queenCee as indicated by the "feature" tag, this probably won't be reviewed for longer as a permament (settings) feature, as it was just an april fools, but if you would still like it on desktop, then you can check out my repo: https://github.com/7twin/devrant-april-fools-2018
