### ISSUE TITLE
Cannot post rant with this content

### ISSUE THREAD

**Issue by NeatNerdPrime** [devRant/devRant#38]
I try to post a serious rant, but i get the message "there was an error posting this rant" Not sure where the error is, this is the rant:

`Like many of us here have not so pleasant encounters with recruitment company's this one really tops it this week! 

First of all: FUCK  YOU VOLTdotCOM, YOU ARE FUCKING HUMAN-TRASH DEGENERATES MAKING THE REDNECK-TRUMP-VOTING-INBREEDER TRASH LOOK LIKE FUCKING INTELLECTUALS!

This just happened 15 minutes ago at the time of this rant. But first a little backstory, this was tuesday

> find job on SO, apply, send them my fancy made CV with everything in it (Lover for linux, puppet course certification, multilingual, everything relevant). Fill in form on SO
> get redirected to volt-eu-com website to apply there, all forms are empty
> a little annoyed but ok i guess, copy/pasta stuff on SO to their site.
> need to register (WTF), register and complete application process.
> receive confirmation e-mail stating "i If you have not heard back from us within 24 working hours, it is either because you did not match our client’s specifications, the position has been withdrawn by the client or filled.", sure, kudo's for communication skills.

This was wednesday
> phone rings, pick up, "hello with NeatNerdPrime"
> "hi this is derpina1, i am calling you because we found your profile on SomeSiteIHaveAbsolyutelyNotHeardOf, i am calling you for an interesting position you will surely like"
> "Errm yeah sure, what's it about?"
> "I am calling you for the exciting position of a 1st line helpdesk support engin.." "Stop right there, i am not a support engineer anymore, i outgrew that, i worked myself as a medior system administrator with full course certification on Puppet, do you have my resumé?"
> "Ow right, it's right here, i received this from derpina0 , for that position as Linux Devops engineer, unfortunately you're not qualified for that position"
> "Ok, why is that?" "Well it seemed you are not experienced in linux and configuration mgmt"...
> MFW.webm ... "Madam, if you have my resume from that job application you are referring to you must have my brand new CV, it's all right there at the first page. " "No i cannot see anything .. (seconds pass) .. Ow yes... you do have that written, but sorry you're just not qualified" - my brains start to hurt at this but i keep my cool
> "madam i am not interested in your first proposal, what i find stunning is that i have a CV clearly stating Linux and ConfMgmt skills and you're saying i'm not qualified because i don't have it?" "Yes that's correct, but i have maybe another position for you, may i call you back? Maybe derpina0 will call you" "Sure madam, have a nice day" * phone convo ends*

wednesday passes, thursday passes, nothing

Today:
> "Hi this is derpina2 calling you from Volt.eu.com i have these two postition for you that is really exciting, First is in a Fortune 500 company bladiabladiebla ... (5 minutes pass and i am too polite to interrupt her script).. And it's for a 'technical consultant position',  "
> "Ok sure, what are the required technical skills?."
> "Windows server, mssql, ad, firewall, scrum, ITIL, Agile SCCM (wtf is agile SCCM), websphere, Kanban, you must go to local customers and install their products on their machines on site, install, configure, must be able to travel..." "Madam , hold on for a moment, you do realise my resumé is oriënted towards Linux, also, you are mixing several SDL methodes together, also you require me to be able to travel, yet you need someone knowledgeable of SCCM, why is that?"
> "Sorry i cannot see your linux qualifications in your resumé, also .." "Wait a moment madam, what date has my resumé? " "It is dated 07/2017" "Does it have 'the neatest DevOps engineer in belgium' as a title?" "Yes it does" "Then you can clearly see my Liniux qualifications, first page!"
> "...."
> "madam?"
> "Oh yes i see...hmm, still, you would be a great match for this permanent position."
> "Not to be rude madam but that is by far not related to my profile, it's an entire mismatch, i would kindly not want to be applied for that. Now, you have a second position for me?"
> "No, this was the only position"
> "But you said you had two at the start of the convo!"
> "You must have misheard that"
What really grinds my gears is someone blaming their own fault at someone else, regardless of the situation.
> "Madam, I have been contacted by your firm 2 times, this week, 2 times for a job opening. you offer me a non-matching position, and it's a permanent position when i applied for contractor positions, please, remove me from your databases."

Meanwhile i search my emails, and i already sent them a removal request 8 years ago.

> "We have a record of you dating 8 years back, i tried to call you on phone n° reallyOldNumber and .." Hold on, you still have that information?" "Yes, it's in our Db" "Madam you have no right to keep that information, i would kindly request to remove all info related to me"
> "Sir you are being really rude, if you would just let me finish, there is no justification for you being angry

BITCHWHATYOUJUSTSAY.GIF

I hang up, EOL`

**Comment by NeatNerdPrime** [comment]
Seems at first sight it falls over single quotes? is this correct?

**Comment by NeatNerdPrime** [comment]
Tried to redact my rant post but to no avail, removed the single quoting and some special characters, ensured it stays within character limit of 5K

`Like many of us here have not so pleasant encounters with recruitment companys this one really tops it this week! 

First of all: FUCK  YOU VOLT.EU.COM, YOU ARE FUCKING HUMAN-TRASH DEGENERATES MAKING THE REDNECK-TRUMP-VOTING-INBREEDER TRASH LOOK LIKE FUCKING INTELLECTUALS!

This just happened 15 minutes ago at the time of this rant. But first a little backstory, this was tuesday

> find job on SO, apply, send them my fancy made CV with everything in it (Lover for linux, puppet course certification, multilingual, everything relevant). Fill in form on SO
> get redirected to volt-eu-com website to apply there, all forms are empty
> a little annoyed but ok i guess, copy/pasta stuff on SO to their site.
> need to register (WTF), register and complete application process.
> receive confirmation e-mail stating "i If you have not heard back from us within 24 working hours, it is either because you did not match our client’s specifications, the position has been withdrawn by the client or filled.", sure, kudos for communication skills.

This was wednesday:
> phone rings, pick up, "hello with NeatNerdPrime"
> "hi this is derpina1, i am calling you because we found your profile on SomeSiteIHaveAbsolyutelyNotHeardOf, i am calling you for an interesting position you will surely like"
> "Errm yeah sure, whats it about?"
> "I am calling you for the exciting position of a 1st line helpdesk support engin.." "Stop right there, i am not a support engineer anymore, i outgrew that, i worked myself as a medior system administrator with full course certification on Puppet, do you have my CV?"
> "Ow right, its right here, i received this from derpina0 , for that position as Linux Devops engineer, unfortunately youre not qualified for that position"
> "Ok, why is that?" "Well it seemed you are not experienced in linux and configuration mgmt"...
> MFW.webm ... "Madam, if you have my resume from that job application you are referring to you must have my brand new CV, its all right there at the first page. " "No i cannot see anything .. (seconds pass) .. Ow yes... you do have that written, but sorry youre just not qualified" - my brains start to hurt at this but i keep my cool
> "madam i am not interested in your first proposal, what i find stunning is that i have a CV clearly stating Linux and ConfMgmt skills and youre saying i am not qualified because i dont have it?" "Yes thats correct, but i have maybe another position for you, may i call you back? Maybe derpina0 will call you" "Sure madam, have a nice day" * phone convo ends*

wednesday passes, thursday passes, nothing

Today:
> "Hi this is derpina2 calling you from Volt.eu.com i have these two postition for you that is really exciting, First is in a Fortune 500 company bladiabladiebla ... (5 minutes pass and i am too polite to interrupt her script).. And its for a *technical consultant position*,  "
> "Ok sure, what are the required technical skills?."
> "Windows server, mssql, ad, firewall, scrum, ITIL, Agile SCCM (wtf is agile SCCM), websphere, Kanban, you must go to local customers and install their products on their machines on site, install, configure, must be able to travel..." "Madam , hold on for a moment, you do realise my CV is oriënted towards Linux, also, you are mixing several SDL methodes together, also you require me to be able to travel, yet you need someone knowledgeable of SCCM, why is that?"
> "Sorry i cannot see your linux qualifications in your CV, also .." "Wait a moment madam, what date has my CV? " "It is dated 07/2017" "Does it have *the neatest DevOps engineer in belgium* as a title?" "Yes it does" "Then you can clearly see my Linux qualifications, first page!"
> "...."
> "madam?"
> "Oh yes i see...hmm, still, you would be a great match for this permanent position."
> "Not to be rude madam but that is by far not related to my profile, its an entire mismatch, i would kindly not want to be applied for that. Now, you have a second position for me?"
> "No, this was the only position"
> "But you said you had two at the start of the convo!"
> "You must have misheard that."
What really grinds my gears is someone blaming their own fault at someone else, regardless of the situation.
> "Madam, I have been contacted by your firm 2 times, this week, 2 times for a job opening. you offer me a non-matching position, and its a permanent position when i applied for contractor positions, please, remove me from your databases."

Meanwhile i search my emails, and i already sent them a removal request 8 years ago.

> "We have a record of you dating 8 years back, i tried to call you on reallyOldNumber and .." Hold on, you still have that information?" "Yes, its in our Db" "Madam you have no right to keep that information, i would kindly request to remove all info related to me"
> "Sir you are being really rude, if you would just let me finish, there is no justification for you being angry"

BITCHWHATYOUJUSTSAY.GIF

I hang up, EOL`

**Comment by DFoxinator** [comment]
What platform are you posting from?

**Comment by NeatNerdPrime** [comment]
I am soooo sorry for not getting back to this sooner. 
To answer your question: It was both on the official App (Android) and on the website. 

The rant in itself is in fact no more relevant since it's been like more then a month ago. Guess i can close this issue. 

Keep up the awesome work @DFoxinator @trogus ,

With kind regards.
