### ISSUE TITLE
[bug] clicking favorite produces delete dialog

### ISSUE THREAD

**Issue by toloveru** [devRant/devRant#380]
When using the devrant.com website in Firefox on Windows 10 (other platforms and browsers might be affected as well but haven't been able to test those), the attempt to favorite a rant causes a confirmation dialog to appear, asking for whether or not you want to delete the rant. When confirming the dialog, the UI makes it seem like the rant is ++'d, brings you back to the feed and eventually favorites the rant.
![image](https://user-images.githubusercontent.com/19938179/38529857-b5ae9e24-3c67-11e8-8e66-6abe5c4d04df.png)

**Comment by 7twin** [comment]
Same issue on chrome

**Comment by varundey** [comment]
Just discovered this. Can confirm for Mac Firefox as well.

**Comment by DFoxinator** [comment]
Thanks, this should be fixed as of a week ago or so.
