### ISSUE TITLE
Don't repeat rants in algo feature

### ISSUE THREAD

**Issue by IwraStudios** [devRant/devRant#4]
I've had lots of moments when i browse algo for a while that i repeat a lot of rants

So an option to remove that would be nice 

I'm not sure if this is still an issue since I always use recent mostly because of the before mentioned reason.

**Comment by DFoxinator** [comment]
Is it possible you've just exhausted the algo and it's showing you "top" rants you've already seen? The algo is built to do that - after you've seen all the recommended/new stuff it has to show, it will start showing you top rants.

**Comment by IwraStudios** [comment]
It is possible but within a few "pages"(mobile) I had already seen some of the same rants, mind you this was maybe a month ago so it might be different now

**Comment by IwraStudios** [comment]
Oh wait i just remembered it it wasn't that alg was 'bad' it was that if i had stopped in algo after a few pages I would see the same posts after closing and opening devrant(on mobile) which was why I stopped browsing algo

**Comment by DFoxinator** [comment]
Closing this, please let me know if it pops up again or is still happening. Thanks.
