### ISSUE TITLE
Newline discarded in sidebar

### ISSUE THREAD

**Issue by DaanVink** [devRant/devRant#413]
Newlines in the content of rants that are displayed on the sidebar are discarded.
This leads to cluttered text

![rant](https://user-images.githubusercontent.com/27428383/39442448-79a94488-4cb1-11e8-8b71-046f8f9d2a4f.PNG)

**Comment by DFoxinator** [comment]
This is intended behavior since we don't want linebreaks on the sidebar that will extend it/cause formatting issues.
