### ISSUE TITLE
Random and weird profile details

### ISSUE THREAD

**Issue by El-Sam** [devRant/devRant#421]
Steps to reproduce issue:

1. go to [devrant search without any term](https://devrant.com/search)

the page will display random data under the **Notifs**, **Interactions** and **Activity** sections regardless of whether the user is logged in or not. 

![image](https://user-images.githubusercontent.com/16857485/39774397-9fb351f4-52f2-11e8-8de5-0f52abfd31d9.png)

This happens on the web app, I'm using Firefox.

**Comment by DFoxinator** [comment]
fixed, thank you!
