### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by WinterCore** [devRant/devRant#427]
Hi
I don't know if this is intended or not.
The last 1-4 posts from a page are showing on the next page after clicking "more rants".

### First page
![capture](https://user-images.githubusercontent.com/8643036/40142720-bb125aa4-5959-11e8-9808-c10bf8fbea8b.JPG)

### Second page (after clicking on "more rants")
![fdfdf](https://user-images.githubusercontent.com/8643036/40142743-d1be3854-5959-11e8-80cc-b1d0def651c4.JPG)

**Comment by digitalmcgrath** [comment]
I believe this is by design. It means that while you were reading the rants on the previous page, more rants were submitted to the site pushing the rants on the bottom of the page to the new page.

**Comment by WinterCore** [comment]
@digitalmcgrath Yea, I think you're right, I haven't thought about that.
