### ISSUE TITLE
[feature-request] queue rants

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#430]
Probably not to be implemented any time soon, but a queue for adding rants would be nice, which could be set to post every 4 hours instead of 2 and limited to some amount, to prevent spam

**Comment by Skayo** [comment]
Possible duplicate of #72

**Comment by 7twin** [comment]
@Skayo oh, I didn't look for "draft", anything else didn't quite get me any results, thanks! closing as duplicate
