### ISSUE TITLE
Show Rant Type as uppercase

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#433]
When creating a collab, you can choose from different project types, and these project types stay in uppercase in the tags section.
But when creating a rant and choosing a rant type, it gets converted to lower case.

Shouldn't it be uppercase too?
F. e.:
random > Random
question > Question

**Comment by Skayo** [comment]
Please set this to a low priority.

**Comment by AlgoRythm-Dylan** [comment]
Collabs are a special case, I assume. I believe rant tags are always lowercase, and having one tag mismatched may be unsettling.
