### ISSUE TITLE
[Feature Request] Show rants by image

### ISSUE THREAD

**Issue by Bobj2018** [devRant/devRant#437]
I would love to see rants that show rants with images/GIFs in the feed.

**Comment by Skayo** [comment]
What? Like twitter?

**Comment by AlgoRythm-Dylan** [comment]
So filter by only having attachments? I don't see this as particularly useful.

**Comment by Bobj2018** [comment]
@AlgoRythm-Dylan After doing some thinking, I will have to agree with you.

**Comment by jonasgeiler** [comment]
@Bobj2018 Close?

**Comment by Bobj2018** [comment]
Yes. @Skayo
