### ISSUE TITLE
[WEB] Unidefined tab title

### ISSUE THREAD

**Issue by MiguelHernandezCh** [devRant/devRant#438]
When I enter a rant details the tab title is undefined 
![image](https://user-images.githubusercontent.com/22020959/40503220-f4fce5be-5f52-11e8-857b-18a1af3d85b4.png)

![image](https://user-images.githubusercontent.com/22020959/40503249-1e2d851a-5f53-11e8-8689-5f1c97e18606.png)

**Comment by 7twin** [comment]
Look at the tags of that rant, it's most likely "undefined" as it couldn't be put in any category like rant etc.

**Comment by DFoxinator** [comment]
Thanks for reporting this! The behavior was actually broken because of some tag changes we made, it was supposed to use the first user-specified tag but was instead using the post category. Should be fixed now.
