### ISSUE TITLE
People want, nah, people _need_ a dark background and a raven!

### ISSUE THREAD

**Issue by RantSomeWhere** [devRant/devRant#450]
On behalf of Floydian, Michelle and the other members of the secret cult of the Black Raven, I demand our Holy Raven to be part of our sacred avatars. The Raven must sit upon our shoulders while darkness surrounds our bodies. Therein lies our destiny, to represent our religion and spread the cult. [EDIT: in a covenant we have finally declared a truce with the Cult of Pink. We now fully support the Guardian of Kyuteness’s plea for a pink background! May our friendship last long.]
[Edit 2: we welcome Team Anarchy to the Kingdom of Devrantia!]

Seriously though, this has been requested for quite a long time now. I’m just posting this on the issue tracker because nobody did so yet.

**Comment by toloveru** [comment]
The black raven is the next billion-dollar feature ❤ please make it happen 🙏

**Comment by Parou** [comment]
@toloveru accident

**Comment by RantSomeWhere** [comment]
Team Raven thanks the Overlords of Devrantia for this gift! Looks awesome!

**Comment by Skayo** [comment]
Will close this. Got implemented. For the darker avatar backgrounds, refer to #469.
