### ISSUE TITLE
[feature-request] Dinamic voting buttons position

### ISSUE THREAD

**Issue by AndreiGr** [devRant/devRant#452]
When browsing rants in the feed, if you want to up-vote a long rant you've read you have to scroll all the way up to the beginning of it in order to do this.
I find this a little frustrating, *especially* when reading quite long rants.

What I suggest is to make the voting buttons scroll with the screen, so when I get at the end of the rant, I can immediately use the voting buttons.

**Comment by Skayo** [comment]
Just double click in the text to up-vote. I think this issue can be closed.

**Comment by Skayo** [comment]
I'll close this for now because it can be achieved by just double-clicking on the text. No need for making this complicated!

**Comment by Skayo** [comment]
In my opinion, down-voting should take the time of scrolling up and clicking on a button.
