### ISSUE TITLE
Webversion adds unnecessary newlines

### ISSUE THREAD

**Issue by Parou** [devRant/devRant#461]
Since the new webversion, everytime I want to make a comment with manual newlines, it adds empty newlines between each line.

Input:
```
1 Begin
2 cuddle @Proximyst
3 Goto 1
4 End
```

Expected:
```
1 Begin
2 cuddle @Proximyst
3 Goto 1
4 End
```

Result:
```
1 Begin

2 cuddle @Proximyst

3 Goto 1

4 End
```

![newline](https://user-images.githubusercontent.com/28531401/41838282-44688880-7860-11e8-9fd6-1c0ab6e91140.PNG)

**Comment by Skayo** [comment]
Annoying bug. Pretty high priority.
Temporary fix is to edit the comment on mobile.

**Comment by Skayo** [comment]
Duplicate of #384
