### ISSUE TITLE
Avatar Builder - Orange/Red Hair not working

### ISSUE THREAD

**Issue by JocPelletier** [devRant/devRant#468]
When you select the Orange/Red Hair color, the avatar hair color remain gray:

![screenshot 358](https://user-images.githubusercontent.com/13203202/42326207-7e049ec0-8036-11e8-9285-ff65152798b5.jpg)

I posted a [devRant](https://devrant.com/rants/1536325/im-new-here-and-yesterday-i-had-the-opportunity-to-create-my-avatar-great-but-i) about this issue :)

**Comment by Skayo** [comment]
Cannot reproduce. 
It appears you have more than 5 hair colors. After the blond (yellow) color, there shouldn't be another one (at least for me?).
Which browser are you using? Do you have any devRant-related user-scripts or user-styles?
Very weird....

**Comment by JocPelletier** [comment]
I have 5 hair colors too, I'm using Google Chrome on Windows. Don't have any scripts/styles. I also tried to remove all my application data, same issue
![screenshot 365](https://user-images.githubusercontent.com/13203202/42893345-1828ed1c-8a82-11e8-813a-81592cf22d86.jpg)

**Comment by trogus** [comment]
There are 5 total hair colors for the male avatar, so that is not the issue (the most recently selected will typically pop to the top of the list though).

I tried reproducing your problem with that specific hair style and starting with grey hair, saving and then switching to red hair, which worked fine for me. On your screenshot you have grey selected, exactly what happens when you select red? It's possible the new avatar image is taking longer to load, if you hit save after selecting red, what do you see then?

**Comment by JocPelletier** [comment]
I have grey selected? On both of my pictures the selected color is "Orange" or something like that, and yes the image is loaded.

**Comment by trogus** [comment]
Yes, that is gray you have selected in both your images. On your 2nd image (most recent comment here), the colors in order are top to bottom: brown, red, black, blonde, gray. Harder to tell the difference on this hair style, try looking at a different hair style with more surface area, and you should be able to distinguish.

**Comment by JocPelletier** [comment]
Ok I see with other hair style, it's gray but the little "round" preview is also Gray for those styles. The issue might be with the preview for this hair style. On my first image I copy/pasted the preview right beside the avatar head and you can see that it's totally different

**Comment by trogus** [comment]
I see the gray thumbnail as a pretty consistent gray with the avatar, but to double-check I used the color picker, and they are pretty much identical minus some variation with jpeg compression. While the colors are very distinctly different for me, your perception of color may be different (20% of men have some form of color-blindness) or your monitor settings may have an impact.

![hair3b](https://user-images.githubusercontent.com/4172987/42903682-a3359a5e-8aa0-11e8-9710-b694caaa975e.png)

**Comment by JocPelletier** [comment]
My eyes are really tricking me on this one!
