### ISSUE TITLE
App Shortcuts for Android 8

### ISSUE THREAD

**Issue by jonasgeiler** [devRant/devRant#476]
On Android 8 (or even 7.1 I think) you have a new feature called "App Shortcuts" which allows you to long press on the app icon in order to access common actions you would do in the app. For example Twitter has shortcuts for tweeting, searching or sending messages.

I thought this would be a great small little feature you could implement. For example to quickly post a rant or searching for rants.

Here are some links that could be useful:
- http://docs.appcelerator.com/platform/latest/?mobile=/api/Titanium.UI.iOS.ApplicationShortcuts
- https://developer.android.com/guide/topics/ui/shortcuts

Greetings!

**Comment by AlgoRythm-Dylan** [comment]
I still feel weird that you can assign priority on your own feature requests

**Comment by Skayo** [comment]
@AlgoRythm-Dylan I don't see a problem here. What's wrong with setting priority 3 on my own feature requests?

**Comment by AlgoRythm-Dylan** [comment]
@Skayo I feel that priority determination, even lowest priority, should be left to either @dfox or @trogus, as they are actually working on the project and their opinion on what should/ should not be done is the only that has any merit.

In other words, this isn't a *request* anymore if you have already given it priority.

**Comment by Skayo** [comment]
I see your point. Because you mentioned dfox (Btw his username on GH is DFoxinator not dfox) he should see this issue soon and decide which priority to use. Although I'm sure he will also give this priority 3...

**Comment by Ewpratten** [comment]
nova launcher supports in android 6+ everything else is 8+
