### ISSUE TITLE
Unable to attach image in a rant [ Android App]

### ISSUE THREAD

**Issue by MSPawanRanjith** [devRant/devRant#477]
Issue :
 
Iam unable to attach any image or gif in a rant.
After clicking on "attach image/gif" button, I can pick the image, and button turns to "Remove Image", but after posting it, only the text content is posted.

I tried modifying , still no.

App Version :
1.12.1.1 , android app

My phone details :
OS : Android Lollipop 5.1
Make : Xiaomi Mi4i
Location : India

**Comment by MSPawanRanjith** [comment]
Is it same in other android versions?
Btw permissions are given, I have  checked it before creating issue.
Please look into it, can't attach any image / gif

**Comment by Irithyll** [comment]
Same for me... 

App version: 1.12.2.2

Phone: OnePlus 5
Android: OmniROM 8.1
Location: Germany

**Comment by Skayo** [comment]
Looks like a high priority issue @DFoxinator.

**Comment by Irithyll** [comment]
So ... now I'm able to attach images again.
Installed new ROM: LiquidRemix (9.1.4) - Android 8.1.0.

**Comment by MSPawanRanjith** [comment]
@Irithyll 
Ohh, then its issue with pre Marshmallow (android 26 ), I don't have a update!:cry:

**Comment by MSPawanRanjith** [comment]
After the new update, Its working now !
Thanks @Skayo @DFoxinator

**Comment by jonasgeiler** [comment]
Okay nice!
