### ISSUE TITLE
Spacer missing, after deleting comment

### ISSUE THREAD

**Issue by pascalwacker** [devRant/devRant#48]
On the Android App, adding a comment to any rant and delete it afterwards. This also delets the "spacer" below the last comment and thus the "social buttons/comment button" are allways overlaying a comment, which makes it difficult to read the last comment.

Rant about it, with confirmation of other users: https://www.devrant.io/rants/759415/bugreport-atdfox-or-attrogus-on-the-android-app-comment-a-rant-and-remove-it-mod

**Comment by DFoxinator** [comment]
This is now fixed because the spacer for comments has been removed in the update we just pushed out. Thanks for reporting!

@cozyplanes I think you were interested in this bug too

**Comment by cozyplanes** [comment]
damn i think you said it was impossible and intended behaviour and wont fix. :rage:
