### ISSUE TITLE
About page crashes

### ISSUE THREAD

**Issue by chabad360** [devRant/devRant#489]
## Bug
This may just be my phone (see details below) but every time I open the about page and scroll down the app crashes.

## System
HTC One M7
Android KitKat (4.4)

**Comment by Skayo** [comment]
Gotta be honest, seems like a phone issue. Maybe the amount of images are leading to a crash?

**Comment by chabad360** [comment]
I don't know, the only image loading issue is with playing GIFs, they __sometimes__ don't render correctly. My phone handles high load pretty well.
