### ISSUE TITLE
Image does not appear after tapping on it

### ISSUE THREAD

**Issue by bdh2991** [devRant/devRant#490]
After tapping on an image I just get brought to a blank screen with the close icon in the corner.  This used to work previously.  Issue persists among all of the different themes.

Pixel XL
Android 9.0

**Comment by Skayo** [comment]
Maybe the image takes longer to load?
This also happened to me a few times. Not sure what was the problem....

**Comment by bdh2991** [comment]
After doing some more testing it does seem like the images are loading now.  But what happens is I have to zoom out for it to appear. 

1) Drill into post with image 
2) Click on image (Blank screen with close button appears) 
3) Zoom out on screen (Image appears)

**Comment by Skayo** [comment]
@bdh2991 First it sounded like a internet issue but due to the zooming thing it could be another issue...

**Comment by DLMousey** [comment]
Having the same problem, Didn't know about the zooming thing - nice find @bdh2991! Can confirm this displays the image after zooming out, I'll see if i can get a recording of it in action.

For the last few weeks i thought it was just refusing to load the images at all.

Only seems to have been happening since the Android 9.0 update, Running a Pixel 2 (not the xl).

**Comment by Skayo** [comment]
@DLMousey Maybe it has something to do with your phones screen updates?

**Comment by DLMousey** [comment]
@Skayo Possibly - i enabled "Show surface updates" (flash entire window surfaces when they update) and opening an image the flashes seem to stop entirely until you start zooming the image, I've got an LG G5 around here somewhere running Android 8.0 i'll dig that out and see if the same issue occurs

**Comment by Skayo** [comment]
@DLMousey Thank you for the information!
Good to know that I've guessed correctly.

@DFoxinator is there a way to force a screen reload? Or something else?

**Comment by DFoxinator** [comment]
Thanks, I will be looking into this, but I'm hoping it gets fixed in the SDK upgrade/overhaul that's coming in our next Android update.

**Comment by DLMousey** [comment]
@Skayo @DFoxinator 
Quick follow up to my last comment - Dug out the G5 running Android 8.0 to test and couldn't reproduce the issue, Seems to be an Android 9.0 change that's screwing with it

**Comment by DLMousey** [comment]
@Skayo @DFoxinator This issue hasn't surfaced again since installing the last couple of updates, everything seems well again. Vote to close?

**Comment by Hunt0** [comment]
I can also confirm this no longer appears to be an issue

**Comment by jonasgeiler** [comment]
Alright, I will close this now. Just comment/reopen if it happens again!
