### ISSUE TITLE
sort/filter notifications by type

### ISSUE THREAD

**Issue by telepathics** [devRant/devRant#5]
it would be nice to have a similar 'filter' toggle for the notifications page as there is one for the main page.  however, instead of giving the option to sort by [algo, recent, or top], the notifications page should have options to filter/sort by filters such as...

- your comment activity ([user] +1'd your comment!)
- your rant activity ([user] +1'd your rant!)
- new rants from users you're subscribed to ([user] posted a new rant!)
- other comment activity (new comments on a rant you commented on!)
- mentions ([user] mentioned you in a comment!)

just a suggestion.  i feel bad whenever i miss a mention/reply or when people i'm subscribed to post a new rant.

**Comment by DFoxinator** [comment]
Thanks for the suggestion - this is definitely a good idea and something we have discussed in the past!

**Comment by DFoxinator** [comment]
This was added a few versions of go. Thanks!
