### ISSUE TITLE
[API] [FEATURE-REQUEST] remove all hastags from the tags

### ISSUE THREAD

**Issue by x-zvf** [devRant/devRant#505]
Hastags in comments are annoying and not the devRant way, so let's remove them.

1. In processing every ner post-rant request, '#' characters should be removed.
2. Update the database to remove existing '#'s. This should be doable with an SQL UPDATE and some regex.

**Comment by nogatco** [comment]
@Skayo , could you add the APi-tag?

**Comment by jonasgeiler** [comment]
While look through some issues again, I noticed that this feature should not be implemented.
If you put a hashtag somewhere, you expect it to stay there, and not just vanish magically.
So this could definitely confuse some people.

I'll close this now. If you feel like this is indeed a feature that should get implemented, reopen this issue and give us a proper reason why this would be needed
