### ISSUE TITLE
Non-Apple computers under 5000++

### ISSUE THREAD

**Issue by metaa** [devRant/devRant#508]
I really don't like how you're forced to either stick to the laptop or choose a Mac when under 5000++. 😢 

Please either make them less Apple-ish or add alternative colors to those computers 🤔

**Comment by TheOct0** [comment]
Encourages you to be more active :)

**Comment by metaa** [comment]
@TheOct0 That's the worst kind of comment one could think of.

**Comment by cactysman** [comment]
So ist this a work in progress now or has it been declined?

**Comment by jonasgeiler** [comment]
@metaa Declined. Who cares if it looks like a MacBook?!? It's virtual! You didn't buy it with your own money!

There are literally 300 other much more important issues here, especially the bugs. As you can see, dfox and trogus don't have enough time to fix or implement all of them, so I try to close all those less important issues (like yours).
Once there are about 100 open bugs left, feel free to reopen this!
