### ISSUE TITLE
How to deal with crime fantasies disguised as a rant?

### ISSUE THREAD

**Issue by k0pernikus** [devRant/devRant#51]
Things just went dark on devRant with this [crime fantasy](https://www.devrant.io/rants/764568/so-i-try-to-stay-away-from-politics-and-the-power-games-being-played-by-the-elit)

Of course, they can "just trying to be funny". Yet it reads also as a strong intent of doing some crimes.

How to report this?

**Comment by filthycoding** [comment]
Downvote and click the small report text.

**Comment by filthycoding** [comment]
![screenshot_20170809-152038](https://user-images.githubusercontent.com/23276523/29123540-62dff1b8-7d16-11e7-9389-86fcd48a559c.png)

**Comment by DFoxinator** [comment]
Like @k0pernikus said, downvoting as offensive/spam is the best option.

Rants like that will get deleted anyway since we have a very strict no politics rule on devRant (unless the politics are directly related to an important dev/technology discussion.

**Comment by DFoxinator** [comment]
By the way, you can read more about our no-politics rule here: https://www.devrant.io/rants/278602/hey-everyone-just-a-note-on-rants-about-politics-weve-had-a-long-standing-policy
