### ISSUE TITLE
[Bug] [Android] [App] Profile comments don't scroll

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#511]
If you go to a profile, then select the comments tab and try to scroll through them - you can't. If you try the same with the other tabs it works though.

Android 7

**Comment by jonasgeiler** [comment]
Jo wtf I can easily reproduce. 😱 This is an really really high priority issue @DFoxinator @trogus

**Comment by DFoxinator** [comment]
Thanks for the report, this has been fixed and released!
