### ISSUE TITLE
++ and -- bug

### ISSUE THREAD

**Issue by MilanVjestica** [devRant/devRant#526]
**Expected behaviour:**
When a user ++'s my rant it goes up by one, and when user --'s my rant it should go down by one.

**Actual behaviour:**
I just notices that I had 7++ on my profile but I only had 4++ on my rant(only rant), so I figured that 7 people clicked ++ but 3 had removed ++ or clicked --. The info on rant is correct but on profile it isnt. 
screenshot: http://prntscr.com/l8o2i9
username: flux

**Description of bug:**

**Steps to reproduce:**
1. ...
2. ...
3. ...

**Platform:** ...
Android(6.0, LG K8 4G)

**Additional Platform Info:**

**App version:** ...
1.12.3.1

**Screenshots:**
http://prntscr.com/l8o2i9

**Comment by MilanVjestica** [comment]
Sorry for bad english

**Comment by jonasgeiler** [comment]
Your comments have ++'s too...
