### ISSUE TITLE
I can’t access my account

### ISSUE THREAD

**Issue by ghost** [devRant/devRant#527]
I have already mailed Devrant about this issue but they dont respond so i feel like i should say this here instead.

I am @HampusMa

I am 100% sure i put in the correct password but it says  ”Invalid login credentials entered. Please try again.”
and when i enter my password into the ”Forgot password” thing i dont get a email. Not even after a long while.

Please help me recover my account

**Comment by jonasgeiler** [comment]
Where are you trying to login? App or Website? Or third-party app? (like devRantron or devRant UWP)

**Comment by ghost** [comment]
> Where are you trying to login? App or Website? Or third-party app? (like devRantron or devRant UWP)

The Devrant website

**Comment by jonasgeiler** [comment]
So is it working now?

**Comment by ghost** [comment]
> So is it working now?

Nope. Turned out Dfox banned me.

**Comment by theabbie** [comment]
@Hampusm I want to know more about this
