### ISSUE TITLE
Clicking at "Rant" should refresh the rant that's currently open

### ISSUE THREAD

**Issue by filthycoding** [devRant/devRant#53]
In the Android app, when you're on the feed, you can press "devRant" at the top to refresh the feed. We should be able to do the same with rants

**Comment by cozyplanes** [comment]
Didn't knew that! 😀

**Comment by DFoxinator** [comment]
This is now available in the new versions of the iOS and Android app which have just been released! (might take a little bit of time for the updates to show up in the app stores.)
