### ISSUE TITLE
No notifications on android

### ISSUE THREAD

**Issue by Dantevg** [devRant/devRant#531]
**Expected behaviour:** 
I get a notification when there is something new

**Actual behaviour:** 
I get no notifications

**Description of bug:** 
No notifs, even if I enable all but the weekly top notification in settings. I think it stopped giving notifications after the last update

**Steps to reproduce:** 
1. Enable notifications 
2. Wait 
3. Wait 
4. Check for notifications in the app

**Platform:**  android app

**App version:**  1.12.3.1

**Comment by jonasgeiler** [comment]
Weird because the last update actually fixed my notifications...

**Comment by Dantevg** [comment]
Sorry, I hadn't seen there already was a new update. I was talking about the previous version, so it's fixed for me now too
