### ISSUE TITLE
Rant vanished

### ISSUE THREAD

**Issue by cobaltron** [devRant/devRant#536]
My registered email address is rajarshila98@gmail.com

I had posted a rant.
I was getting ++ on it and now suddenly it has disappeared from my profile.

Link: https://devrant.com/rants/1887004

**Comment by jonasgeiler** [comment]
Probably removed because you didn't follow the rules. What was it about?

**Comment by jonasgeiler** [comment]
@dfox Can you check his account?

**Comment by DFoxinator** [comment]
If it was removed, it was because it violated our rules or might have been a non-first-occuraece of obvious miscategorization.
