### ISSUE TITLE
Inner panels şn notification tab doesn't work

### ISSUE THREAD

**Issue by Abrifq** [devRant/devRant#539]
**Expected behaviour:**
Being able to use inner tabs in notification panel

**Actual behaviour:**
Can't use inner tabs in notification panel, just the notifications and outer(bottom) tabs

**Description of bug:**
Using Android 8.0 and I opened the app, did the casual stuff and is broke

**Steps to reproduce:**
1. ...Open the app
2. ...Open Notifications
3. ...Click Mentions
4. ...Enter a rant from there
5. ...Exit rant
6. ...It should not work now

**Platform:** ...
Android 8.0
SM-J330F (a.k.a Samsung Galaxy J3 Pro 2017)

**Additional Platform Info:**

**App version:** ...
1.12.4.1

**Screenshots:**

**Comment by jonasgeiler** [comment]
Cannot reproduce

**Comment by Abrifq** [comment]
Interestingly I can't too. Maybe I was too deep ranting.
