### ISSUE TITLE
Blinking lines on "Hello Darkness, My Old Friend"

### ISSUE THREAD

**Issue by Teyler7** [devRant/devRant#551]
**Expected behavior:** When scrolling through iOS DevRant on "Hello Darkness, My Old Friend", the lines that separate posts should just be there and out of the way.

**Actual behavior:** Instead, when scrolling, occasionally the post separating lines blink from grey to white while the scroll is happening.

**Description of bug:** I am using DevRant on an iPhone XR. I feel like this impacts more people on iOS than just me. I love the dark theme, but this made me switch back to light theme for the time being. Heck I am contemplating DevRant ++ just for the darker theme ;)

**Steps to reproduce:**
1. Change the theme to "Hello Darkness, My Old Friend"
2. Scroll through the main tab and watch for occasional blinking lines

**Platform:**  iOS

**Additional Platform Info:** iOS 12.1.4. iPhone XR

**App version:** 1.12.2

**Screenshots:**

**Comment by C0D4-101** [comment]
Same occurs on Blackest Black theme, became to irritating to scroll I had to revert back to Darkness my old friend although it still occurs but not as distracting.

iPhone XR IOS 12.3.1

Preview of issue:
https://vimeo.com/345143843

**Comment by Teyler7** [comment]
Closing as this is a Stale Issue. Hope you are doing well Dev Rant team.
