### ISSUE TITLE
Notifs unavailable

### ISSUE THREAD

**Issue by eklavyadev** [devRant/devRant#610]
Not receiving notifs when mentioned in a comment, neither of subscribed user's rants

**Comment by eklavyadev** [comment]
Not receiving notifs when mentioned in a comment, neither of subscribed user's rants

**Comment by C0D4-101** [comment]
Linking rant with context / discussion.

https://devrant.com/rants/4592358/am-i-the-only-one-who-isnt-getting-any-mention-notification-and-even-count-is-up
