### ISSUE TITLE
Feature request: Rant it later!

### ISSUE THREAD

**Issue by balaianu** [devRant/devRant#70]
Hello,

As I said in my rant today (https://www.devrant.io/rants/785220/just-thought-of-a-cool-feature-for-devrant-rant-it-later-i-get-why-the-2-hours-l), I thought of a cool feature for devRant: rant it later!

I get why the 2 hours limit between rants exists, but it would be so cool to write a rant and the app to self post it after the 2 hours limit expires!

And it could also give a notification that the rant was posted.

What do you think?

Is this something you would wanna see/add in the app?

And as [JonnyCodewalker](https://www.devrant.io/users/JonnyCodewalker) said in a comment: One could even make it so that the amount of rants you can queue up scales with your standing.

Hope this helps! :)

**Comment by faraazahmad** [comment]
I think this is a cool idea. But, this may possibly reduce the number of people becoming members.
Since DevRant is self-funded, I guess let's show our support and become members instead. This feature could be something for a third party DevRant client.

Just my two cents.

**Comment by balaianu** [comment]
Umm... I fail to see how this could keep or discourage people from becoming members...

All this would do is allow someone that just ranted something and has another rant he/she wants to post to queue it to get auto-posted after the existing 2 hours limit devRant has until someone can post a new rant (reasons for the limit are explained in the app, and make sense, they are not part of my idea and are already in place).

If I am missing something, please be more specific :)

**Comment by Bear-with-me** [comment]
I think what @faraazahmad is referring to is the fact that if you support devRant the time between ranting is reduced from 2 hours to 1 hour, which could be seen as an incentive to support devRant. A feature which causes that wait time to have less weight to it could correlate to less people supporting devRant.

**Comment by faraazahmad** [comment]
yeah, pretty much

**Comment by jaseonline** [comment]
Need this feature 😂

**Comment by DFoxinator** [comment]
Going to close this for now. We feel that rants are not meant to be like tweets in that you’re firing them off, and we don’t want to encourage automated posting. However, we will be improving the auto-save draft feature :)

**Comment by jaseonline** [comment]
Nawww
