### ISSUE TITLE
Repeatedly switching between tabs in quick succession from bottom nav shows blank page 

### ISSUE THREAD

**Issue by faraazahmad** [devRant/devRant#74]
I'm using the Android app on android 7.0
Repeatedly switching between any 2 tabs in quick succession displays a blank page at one point. 

I think it has something to do with either the server's response time, or the view render time in the app.

**Comment by faraazahmad** [comment]
Here's the corresponding rant

https://www.devrant.io/rants/786861/devrant-issue-when-you-repeatedly-switch-between-tabs-in-quick-succession-this-b

**Comment by filthycoding** [comment]
It's most probably an app issue.

**Comment by LoganS1** [comment]
issue #7 is also about this
