### ISSUE TITLE
Feature request: Add black amoled theme to the app

### ISSUE THREAD

**Issue by kvsjxd** [devRant/devRant#75]
Hello,
It would be really nice if we can also have a complete black theme in the app for amoled screens. Black theme will save battery on mobile devices, would give an awesome UX, and also would go easy on eyes.

**Comment by filthycoding** [comment]
Basically a dark dark theme :P

**Comment by kvsjxd** [comment]
I mean #000000 specifically.

**Comment by DFoxinator** [comment]
This is actually in-progress. @trogus is working on it. The black theme will be for devRant++ members only though, or at least that's our thought right now.

**Comment by kvsjxd** [comment]
One more reason to become devRant++ member 👍🏻

**Comment by DFoxinator** [comment]
Added in update that was just released!
