### ISSUE TITLE
Swag Store

### ISSUE THREAD

**Issue by olback** [devRant/devRant#76]
## Feature request. 

I wonder if it would be possible to add the ability to purchase Swag within the app and use Google play in-app purchases as a payment option. This would allow people without a debit/credit card to buy swag. I have no idea how hard it would be to add other payment methods as well, such as PaySafeCard. 

Thanks.

**Comment by m1guelpf** [comment]
If you add bitcoin, you have a client here!

**Comment by ivanvinski** [comment]
Even though I have a debit card, I think it would be really neat to be able to buy swag within the app through Google Play. :+1:

**Comment by DFoxinator** [comment]
This is a good idea, but as far as I can tell, not realistic for us any time in the near future. We have very small margins as it is, and we wouldn’t be able to offer most items with the 30% cut Google would take. If you have any other ideas please let me know, going to close this for now.

**Comment by trogus** [comment]
The app stores only take a % of digital goods (videos, e-books, online community subscriptions, etc.) but not physical products, so should be doable, just not sure how our Shopify store would work with that payment method.

**Comment by DFoxinator** [comment]
Actually, I’m pretty sure you can’t even use in app purchases to sell physical products. I don’t think it’s allowed.
