### ISSUE TITLE
iOS tabs get pushed halfway down the screen when using hotspot

### ISSUE THREAD

**Issue by mmdelez** [devRant/devRant#8]
Only tested on iPhone 7 (not plus) but if I'm using my hotspot and the little blue bar appears on top of the screen telling me how many devices are connected, the iOS tab bar gets pushed halfway down the screen if selected any tab other than the leftmost tab. This seems to be a tricky thing for apps to handle correctly. Most apps seem to just hide the blue bar which I prefer.

**Comment by mmdelez** [comment]
I should probably mention I'm on iOS 10.3.2

**Comment by heyheni** [comment]
Same on the Iphone 6s. In future ios versions the blue bar will be used for other things too.

**Comment by DFoxinator** [comment]
Should be fixed in 1.11.0. Thanks.
