### ISSUE TITLE
Algorithm suggests already viewed and ++'ed rants

### ISSUE THREAD

**Issue by somerandomd3v** [devRant/devRant#80]
This just happened to me. I guess it wouldn't be hard to solve this. 
![Heres a screenshot ](https://image.ibb.co/gHedp5/Screenshot_20170827_192637.jpg)
 

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DFoxinator** [comment]
This is what happens when the algo is out of rants to show you. Unfortunately right now the only other solution is showing something that says "Out of rants."

**Comment by DFoxinator** [comment]
Closing as expected behavior.
