### ISSUE TITLE
Loading screen at supporter screen not matching

### ISSUE THREAD

**Issue by filthycoding** [devRant/devRant#83]
Something I'd personally give the lowest priority available:

![screenshot_20170904-185120](https://user-images.githubusercontent.com/23276523/30034575-8794dc76-91a2-11e7-8da4-99bea663030e.png)

As you can see, the loading screen doesn't have the usual background around the bouncing :/ icon.

**Comment by cozyplanes** [comment]
ok, one more, in about screen. it looks strange as well

**Comment by cozyplanes** [comment]
just a ref tho

**Comment by DFoxinator** [comment]
This has been fixed
