### ISSUE TITLE
Search rants by id

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#86]
I have asked this a LONG time ago, but still not available.

Can you add the search option to search rant by id?

**Comment by DFoxinator** [comment]
Thanks for the great suggestion - this should now be working!

**Comment by cozyplanes** [comment]
it took more than 6 months. phew.

**Comment by Skayo** [comment]
@cozyplanes
Calm down. He is only a human...

**Comment by cozyplanes** [comment]
I thought he was a fox... (smirking face)
