### ISSUE TITLE
Subscribe to rant feature 

### ISSUE THREAD

**Issue by sasin91** [devRant/devRant#90]
A subscribe to rant feature would be welcome.
This feature would mitigate the need for people to "bump" rants, to receive updates :)

I imagine a user_rants pivot table would suffice.
but for brevity, this could be promoted to a rant_subscriptions model? :)

**Comment by cozyplanes** [comment]
Possible duplicate of #6

**Comment by cozyplanes** [comment]
@DFoxinator where are you? cant see you latelu

**Comment by DFoxinator** [comment]
@sasin91 sorry I told you to make this, didn't realize it was already issued - I'm going to change the title of https://github.com/devRant/devRant/issues/6 to be more searchable.
