### ISSUE TITLE
Notifications not showing in Edge

### ISSUE THREAD

**Issue by JamJar00** [devRant/devRant#92]
When viewing devRant in Edge the badge on the notifications link in the menu is showing as a blank circle
![image](https://user-images.githubusercontent.com/5931310/30386938-034d60f2-98a3-11e7-85e4-0858dee92c5d.png)
And the notifications do not display when viewing the notifications page
![image](https://user-images.githubusercontent.com/5931310/30386988-222ae1e8-98a3-11e7-925a-e9a857f30537.png)

When viewing the developers console on the notifications page it shows a single error which I expect caused the problem
![image](https://user-images.githubusercontent.com/5931310/30387052-5770c336-98a3-11e7-8f85-9ecf0eaff437.png)

It appears to work fine in Firefox on my PC, occurred using Microsoft Edge 40.15063.0.0 and Microsoft EdgeHTML 15.15063.

**Comment by DFoxinator** [comment]
Thank you for the very thorough bug report.

Apparently we're using some JavaScript that isn't supported in Edge. I'm trying to figure out a substitute and will try to update shortly. Thanks again!

**Comment by JamJar00** [comment]
[It seems this will be sorted soon-ish by the developers at Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8993198/).

**Comment by DFoxinator** [comment]
Thanks @JamJar00, I had been monitoring, glad they added the functionality. Going to close this.

**Comment by JamJar00** [comment]
This appears to still be an issue with the new website just so you know. The fix seems to still be unreleased.
