### ISSUE TITLE
Moderated editing after editing period

### ISSUE THREAD

**Issue by filthycoding** [devRant/devRant#95]
**_Sometimes, even the extended 30 minute editing period isn't enough._** 

Since I know that allowing infinite editing would create many misunderstandings, as well as server load (images for each rant get created AFAIK, and they have to be updated each time), I would love to suggest:

### Moderated editing

The concept is simple: People can volunteer as editing moderators. After 5 (or for supporters, 30) minutes, edits have to be approved by a moderator before they get applied (They can also be rejected). You also have to provide a reason for editing then, and you are not allowed to send editing requests (in general, per account, not per rant/comment) more often than in 10 minute intervals (to avoid moderator/server spam)

To avoid moderators abusing their power or putting unneccessary load on the servers, there should be an audit log, visible to all moderators. As soon as mods suspect that someone is abusing their moderator rank, they should be able to report this to David Fox.

That's it for my idea, it might take some work to implement it though. I just thought it would be a nice idea :wink:

EDIT: Maybe only people with a certain reputation level should be able to volunteer, perhaps starting at 10,000?

**Comment by Skayo** [comment]
Overly complicated.
DevRant is a social media, not a forum...

**Comment by cozyplanes** [comment]
just saying, but i am sure david will die implementing this in titanium

**Comment by filthycoding** [comment]
@cozyplanes Well, it was just an idea, an approach to devRant++ subscribers that see a mistake in their post/comment at 33m. I get that it might be _really_  difficult to implement that.

**Comment by DFoxinator** [comment]
Thanks for the suggestion. While I think it's a cool idea, I think the exponentially simpler solution is just making the edit time window 1 hour for devRant++ members. I think that helps a lot more cases and honestly we've yet to (knock on wood) really see any abuse of the editing feature. Unless there's any objections, I think that's what we can do right now.

**Comment by RekkyRek** [comment]
Also, I think there should be a way to view previous edit history

**Comment by Skayo** [comment]
@RekkyRek If the previous versions of a rant would be stored in the database too, the size of the database would grow **much**  faster than it already does.

**Comment by DFoxinator** [comment]
I'm going to close this. While I think it's a good suggestion, this pretty much never comes up as a significant issue and dedicating the time to it wouldn't be worth it I don't think and I think it could do more harm than good.
