### ISSUE TITLE
'To Top' & 'To Bottom' Buttons on long Rants.

### ISSUE THREAD

**Issue by Jaakuza** [devRant/devRant#97]
This is a feature Request for the Mobile Version of DevRant. Specifically Android.

I find it to be a bit annoying that I have to swipe up a few times, when checking out a long Rant.
Small Arrow-Buttons at the Side of the Screen on lets say Rants with over 10 Comments would be nice.

**Comment by cozyplanes** [comment]
possible duplicate with #66

**Comment by DFoxinator** [comment]
Both scroll to top and scroll to bottom are available in the new versions of the iOS and Android app which have just been released! (might take a little bit of time for the updates to show up in the app stores.)

**Comment by cozyplanes** [comment]
yeah!
