### ISSUE TITLE
Not sure: API collabs issue, or user error?

### ISSUE THREAD

**Issue by olegrumiancev** [devRant/devRant#98]
Hi guys,
Am trying out the collabs portion of the API and it seems to ignore "skip" parameter that I specify
URLs that am using are 
1) https://www.devrant.io/api/devrant/collabs?app=3&limit=5
2) https://www.devrant.io/api/devrant/collabs?app=3&limit=5&skip=2

Those two seem to return same results, is this correct? How to we instruct API to skip some collabs for paging?

**Comment by DFoxinator** [comment]
Excellent catch, thanks for reporting! This was a bug with the collabs API endpoint for logged out fetches - apparently I forgot to add the skip parameter to the database query for that case. Should be fixed now :)
