### ISSUE TITLE
Theme name

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#99]
Just a stupid idea.
Blackest black-> RantaBlack (in succession to vantablack)
Close it when you think it is stupid :stuck_out_tongue_closed_eyes:

**Comment by RekkyRek** [comment]
I think this is a great suggestion lol

**Comment by cozyplanes** [comment]
@DFoxinator is this being implemented someday? ^^

**Comment by DFoxinator** [comment]
I think we're going to keep these as-is. I think for new users the other names can be a little confusing.

**Comment by cozyplanes** [comment]
Ok then, thanks!

2018-01-18 14:51 GMT+09:00 David Fox <notifications@github.com>:
